### PR TITLE
Static type checking fixes

### LINKED ISSUE #4535: A "py.typed" marker
Hi all,

I was wondering if there's a specific reason that neither `allennlp`, nor `allennlp-models` include an empty marker file named `py.typed` in their respective python package root directories, as that file is required to mark a package as "PEP-561 compliant", which gives static code analysis tools like mypy the go-ahead to do type inference.

Otherwise, I am currently forced to clone the repo locally, add the marker file, and `pip install -e` to stop mypy from complaining that stubs are missing for `allennlp`.

### PR DESCRIPTION
**Pull request by davidatbu**
Small type annotation fixes. 

PS: I had `isort` runnning automatically which reordered some imports in the files I modified, hope that's ok(didn't see anything in CONTRIBUTING.md about import order).

Closes #4535 .

### CODE REVIEW

**Comment by davidatbu** [comment]
@AkshitaB , CI is failing because I didn't update  CHANGELOG.md, and because code coverage(of the diff?) is below 90%.

Lmk if you think I should update CHANGELOG.md. About code coverage, no idea what to do.

**Comment by dirkgr** [comment]
What's going on with this PR? Can we get it in? I'm a big fan of having this!

**Comment by epwalsh** [comment]
I think `py.typed` may need to be listed in the `package_data` section of `setup.py`. See https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages

**Comment by davidatbu** [comment]
@epwalsh , @dirkgr , sorry for the radio silence. There's a `include_package_data=True` arg passed to `setup()`, which does the same thing as `package_data = { "": [ 'py.typed'] }` in our case. I tested this by doing `pip install  .` in a fresh virtual env, and I found the `py.typed` marker in the installed dir.

**Pull request merged**
