### PR TITLE
Modify docstring to add example for initializing weights from a pretrained model

### PR DESCRIPTION
**Pull request by skeshaw**
In light of discussion on [this issue](https://github.com/allenai/allennlp/issues/3144), modified docstring to include example for initializing weights for all parameters using a pretrained checkpoint without passing named parameters.

### CODE REVIEW

**Comment by skeshaw** [comment]
Can someone help me here? I am not sure why the build is failing; I haven't even changed the code per se.

**Comment by nelson-liu** [comment]
here's the error:

```
[10:02:39][Step 7/10] 
[10:02:39][Step 7/10] Traceback (most recent call last):
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 276, in build_main
[10:02:39][Step 7/10]     app.build(args.force_all, filenames)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 346, in build
[10:02:39][Step 7/10]     self.builder.build_update()
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 299, in build_update
[10:02:39][Step 7/10]     len(to_build))
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 311, in build
[10:02:39][Step 7/10]     updated_docnames = set(self.read())
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
[10:02:39][Step 7/10]     next(self.gen)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/site-packages/sphinx/util/logging.py", line 219, in pending_warnings
[10:02:39][Step 7/10]     memhandler.flushTo(logger)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/site-packages/sphinx/util/logging.py", line 184, in flushTo
[10:02:39][Step 7/10]     logger.handle(record)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/logging/__init__.py", line 1454, in handle
[10:02:39][Step 7/10]     self.callHandlers(record)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
[10:02:39][Step 7/10]     hdlr.handle(record)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/logging/__init__.py", line 861, in handle
[10:02:39][Step 7/10]     rv = self.filter(record)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/logging/__init__.py", line 720, in filter
[10:02:39][Step 7/10]     result = f.filter(record)
[10:02:39][Step 7/10]   File "/usr/local/lib/python3.6/site-packages/sphinx/util/logging.py", line 404, in filter
[10:02:39][Step 7/10]     raise SphinxWarning(location + ":" + message)
[10:02:39][Step 7/10] sphinx.errors.SphinxWarning: /local/deploy/agent2/work/98197cf33cb401e5/allennlp/nn/initializers.py:docstring of allennlp.nn.initializers.PretrainedModelInitializer:35:Unexpected indentation.
[10:02:39][Step 7/10] 
[10:02:39][Step 7/10] Warning, treated as error:
[10:02:39][Step 7/10] /local/deploy/agent2/work/98197cf33cb401e5/allennlp/nn/initializers.py:docstring of allennlp.nn.initializers.PretrainedModelInitializer:35:Unexpected indentation.
[10:02:39][Step 7/10] make[1]: *** [check] Error 2
[10:02:39][Step 7/10] make: *** [html-strict] Error 2
```

To fix this, i'd use the `code-block` directive in sphinx: https://www.sphinx-doc.org/en/1.5/markup/code.html .

**Comment by skeshaw** [comment]
I can't quite understand the error message. Does it contain any information as to in which line this error occurs?
Also, does this error prevent the code from running properly? I am just trying to understand why this occurred and how it affects the functionality of the library.

**Comment by nelson-liu** [comment]
Yes, the indentation is problematic in the following part of the docstring:

```
       [".*",
           {
               "type": "pretrained",
               "weights_file_path": "best.th",
               "parameter_name_overrides": {}
           }
       ]
```

The error occurs when sphinx tries to build the documentation for the library from the docstring, and find that it is potentially malformed. You can run this same check yourself if you run `python scripts/verify.py check-docs build-docs`.

You can modify your PR to follow the formatting here, and it should work:

https://github.com/allenai/allennlp/blob/cca99b9191fe1787c34c1cc361c05e09d15bdbfe/allennlp/predictors/event2mind.py#L21-L27

**Comment by nelson-liu** [comment]
And here's what the section of the doc looks like when it's formatted in a way that makes sphinx happy:

https://allenai.github.io/allennlp-docs/api/allennlp.predictors.html#event2mind

**Comment by nelson-liu** [comment]
I think you want something like:

```
    To initialize weights for all the parameters from a pretrained model (assuming their names
    remain unchanged), use the following instead:

        .. code-block:: js

            [".*",
                {
                    "type": "pretrained",
                    "weights_file_path": "best.th",
                    "parameter_name_overrides": {}
                }
            ]
```

I think another issue right now is that the code block indentation isn't a multiple of a 2...

**Comment by skeshaw** [comment]
Thanks for your comments. It's my first time here, and wasn't even aware of all the checks required. This should help me as well in the future.

**Comment by nelson-liu** [comment]
No worries, it's certainly rather opaque :) thanks for taking the time to make the change.

**Pull request merged**
