### PR TITLE
ensure torch always up-to-date in CI

### PR DESCRIPTION
**Pull request by epwalsh**
This adds a step in CI that will ensure the current installed version of PyTorch is the most recent allowed version PyTorch according to our dependency specification in `setup.py`.

This is needed because we have to hard-code the torch installation steps in some places, so dependabot updates don't necessarily change the version of PyTorch used in CI.

### CODE REVIEW

**Review by dirkgr — COMMENTED** [review]
Is there no `pip` incantation that can do this? It seems brittle to parse the torch version string like that.

**Comment by epwalsh** [comment]
> Is there no pip incantation that can do this? It seems brittle to parse the torch version string like that.

Another option would be to parse the output of `pip show torch` or `pip freeze | grep torch`. But that seems even more brittle.

**Comment by dirkgr** [comment]
What I mean is, isn't there a pip incantation that can install the highest allowed version of torch? Does `pip install torch --upgrade` do it?

**Comment by epwalsh** [comment]
That works with any other dependency but not with torch since the exact version we need depends on the CUDA version available, and pip is not aware of that.

**Review by dirkgr — APPROVED** [review]
Well, I'm not excited about the brittleness, but I don't have a better idea either.

**Comment by dirkgr** [comment]
Well what do you know, it broke.

**Pull request merged**
