### PR TITLE
Add configs for tasks in ELMo paper, with and without ELMo

### PR DESCRIPTION
**Pull request by nelson-liu**
This PR tries to round out the configs necessary for reproducing or at least getting close to the baseline and baseline+elmo numbers reported in the [ELMo paper](https://arxiv.org/abs/1802.05365).

Note that almost all of the experiments for the ELMo paper were done before AllenNLP existed.  The models in AllenNLP are re-implementations of things that were typically originally written in tensorflow code.  We haven't had the resources to tune the AllenNLP implementations to match the existing performance numbers yet; if you are able to do this for some of the models and submit back a tuned model, we (and many others) would greatly appreciate it.

here's a table with each task and the configs you can use in allennlp to train. The configs are located in the [`training_config/`](https://github.com/allenai/allennlp/tree/master/training_config) folder.

Task | Baseline Config | Baseline + ELMo config | Notes
--- | --- | --- | ---
SQuAD | N/A | N/A | The SQuAD model is from [Clark and Gardner 2017](https://arxiv.org/abs/1710.10723). We're working on adding this model to allennlp, but the original code used to run the experiments is in [this repo](https://github.com/allenai/document-qa/tree/master/docqa/elmo)
SNLI | `esim.json` | `esim_elmo.json` | This configuration is modified slightly from the one used in the ELMo paper, but the numbers should be quite comparable. See [the comment in the config](https://github.com/allenai/allennlp/blob/master/training_config/esim.json#L2-L10) for more details.
SRL | `semantic_role_labeler.jsonnet` | `semantic_role_labeler_elmo.jsonnet` | There's also a config that uses the ELMo trained on 5.5B tokens.
Coref | `coref.jsonnet` | `coref_elmo.jsonnet` | The model in AllenNLP is missing some additional features in the original model. The original code is at [kentonl/e2e-coref](https://github.com/kentonl/e2e-coref)
NER | `ner.jsonnet` | `ner_elmo.jsonnet` | -
SST-5 | `biattentive_classification_network.json` | `biattentive_classification_network_elmo.json` | -

hopefully this helps folks looking to reproduce the ELMo paper (which might need a bit more tuning, so please contribute if you take the time to do so!) or build upon it.

Also happy to rename these configs / reorganize them in whatever way you all might see fit, these names were pretty arbitrary (mostly `model/task + elmo`).

cc: @mdelhoneux / @miguelballesteros

### CODE REVIEW

**Comment by mdelhoneux** [comment]
This is great thanks!!

**Comment by mdelhoneux** [comment]
Quick question @nelson-liu : the elmo configuration for SRL recommends using alternating_lstm_cuda as encoder type but doing so results in a Configuration error:
```
allennlp.common.checks.ConfigurationError: "alternating_lstm_cuda not in acceptable choices for model.encoder.type: ['intra_sentence_attention', 'multi_head_self_attention', 'stacked_self_attention', 'pass_through', 'gru', 'lstm', 'rnn', 'augmented_lstm', 'alternating_lstm', 'stacked_bidirectional_lstm', 'alternating_highway_lstm_cuda']"
```

Is it the alternating_highway_lstm_cuda that should be used?

**Comment by nelson-liu** [comment]
@mdelhoneux oops, you're right --- `alternating_highway_lstm_cuda` looks like the one to use. I'll modify the config without elmo / submit a PR to correct this typo for the configs that are already in the repo.

Note that `alternating_highway_lstm_cuda` might not work out of the box, since it uses a custom CUDA kernel that was broken in pytorch 0.4 (see #1456). You might have to go to your allennlp install directory (find it with `python -c "import allennlp; print(allennlp.__file__)"`), and run `make.sh` in the `custom_extensions` folder ([here](https://github.com/allenai/allennlp/tree/master/allennlp/custom_extensions)) to recompile it to work.

**Comment by mdelhoneux** [comment]
Thanks! That issue seems to be saying that that encoder is not currently working though, right?
I followed your suggestion (+ had to git pull and reinstall allennlp before running make.sh) and I so far have not managed to get the model to work (I run into cuda runtime errors so not sure if it is the same issue as the one reported).

Note I first had this error:
```
TypeError: __init__() got an unexpected keyword argument 'use_input_projection_bias'                                                                                              
```
I removed `"use_input_projection_bias": false` from the encoder configuration and it seemed to fix it.

Let me know if you get the model to work!

**Comment by mdelhoneux** [comment]
Ah great thanks! I'll give that a try!

**Comment by mdelhoneux** [comment]
Quick question again @nelson-liu : how slow would it be to train the alternating_lstm? From the comment it sounds like it would be prohibitively slow but since it works out of the box, it might be the easiest.

**Comment by mdelhoneux** [comment]
Btw if you have the configuration file for SRL with stacked_self_attention which reproduced the results, would be of great help.

**Comment by matt-peters** [comment]
@markn can provide more details, but I don't believe we ever tuned the Transformer SRL model carefully enough to reproduce the Tan et al. AAAI result.  If your goal is to reproduce the SRL result from "Deep contextualized word representations", then I'd recommend downgrading your allennlp to the latest working version of `alternating_lstm_cuda` (before the pytorch 0.4 upgrade?).  The non-CUDA version is horribly slow (the CUDA version too is quite slow, but considerably faster).

**Comment by mdelhoneux** [comment]
Thanks, I'll try that. If there is a version that you know is working that you can point me to, it would be very helpful. I just tried downgrading to just before the move to 0.4 but now the dataset reader seems to be working differently, it is not accepting the directory of SRL annotated files as 'train_data_path' like it is in the current version. (I get a 'file not found' error which I was not getting before)

**Comment by mdelhoneux** [comment]
Do you mean `alternating_highway_lstm_cuda` or was `alternating_lstm_cuda` really a thing at some point? I downgraded to just before the upgrade to pytorch 0.4.0 (b26031db4f27d606146f7d5820b1e884559bd4d4) and there is no `alternating_lstm_cuda` in the model encoder types. I tried `alternating_highway_lstm_cuda` instead like we discussed above with Nelson and I haven't got it to work so far. With changing the encoder type as only change to `training_config/semantic_role_labeler.json` I get a `TypeError: __init__() got an unexpected keyword argument 'use_highway'`, and if I remove `"use_highway": true`, I get a maximum recursion depth exceeded error. I guess I need to do more changes to the training configuration file? Some pointers about this would be very helpful.

**Comment by nelson-liu** [comment]
@mdelhoneux  sorry for the delay! Is the recursion depth error you're seeing the same as this one: https://github.com/allenai/allennlp/issues/1660 ? regardless, you shouldn't see it if you follow the instructions below since that error only shows up on the latest version of allennlp.

So first off, you're right that it's `alternating_highway_lstm_cuda` -- `alternating_lstm_cuda` was never a thing.

I seem to have gotten the SRL model to train by doing the following:

1. create a new virtualenv or conda env for allennlp 0.4.3 (the last release prior to the 0.4 change that broke `alternating_highway_lstm_cuda`

```
conda create -n allennlp043 python=3.6
```

2. install allennlp 0.4.3

```
pip install allennlp==0.4.3
```

3. Use the following SRL config. It's exactly the same as https://github.com/allenai/allennlp/blob/v0.4.3/training_config/semantic_role_labeler.json , but i removed the `use_highway` argument and changed the encoder type to `"type": "alternating_highway_lstm_cuda"`.

```
{
  "dataset_reader":{"type":"srl"},
  "train_data_path": "conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/train/",
  "validation_data_path": "conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/development",
  "model": {
    "type": "srl",
    "text_field_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim": 100,
        "pretrained_file": "https://s3-us-west-2.amazonaws.com/allennlp/datasets/glove/glove.6B.100d.txt.gz",
        "trainable": true
      }
    },
    "initializer": [
      [
        "tag_projection_layer.*weight",
        {
          "type": "orthogonal"
        }
      ]
    ],
    "encoder": {
      "type": "alternating_highway_lstm_cuda",
      "input_size": 200,
      "hidden_size": 300,
      "num_layers": 8,
      "recurrent_dropout_probability": 0.1
    },
    "binary_feature_dim": 100
  },
  "iterator": {
    "type": "bucket",
    "sorting_keys": [["tokens", "num_tokens"]],
    "batch_size" : 80
  },

  "trainer": {
    "num_epochs": 500,
    "grad_clipping": 1.0,
    "patience": 20,
    "validation_metric": "+f1-measure-overall",
    "cuda_device": 0,
    "optimizer": {
      "type": "adadelta",
      "rho": 0.95
    }
  }
}
```

4. Train with the config however you normally would (e.g. `allennlp train <jsonpath> -s srl_test`.

Let me know if that still doesn't work --- I didn't run the training to completion, only verified that it started training and that the GPU was being used. Sorry this is such a hassle!

**Comment by nelson-liu** [comment]
oops, and here's a training config that is a modification of the one above in order to have it use ELMo:

```
{
  "dataset_reader":{
    "type":"srl",
    "token_indexers": {
      "elmo": {
        "type": "elmo_characters"
      }
    }
  },
  "train_data_path": "${SRL_TRAIN_DATA_PATH}",
  "validation_data_path": "${SRL_VALIDATION_DATA_PATH}",
  "model": {
    "type": "srl",
    "text_field_embedder": {
      "elmo": {
        "type": "elmo_token_embedder",
        "options_file": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json",
        "weight_file": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5",
        "do_layer_norm": false,
        "dropout": 0.1
      }
    },
    "initializer": [
      [
        "tag_projection_layer.*weight",
        {
          "type": "orthogonal"
        }
      ]
    ],
    "encoder": {
      "type": "alternating_highway_lstm_cuda",
      "input_size": 1124,
      "hidden_size": 300,
      "num_layers": 8,
      "recurrent_dropout_probability": 0.1
    },
    "binary_feature_dim": 100
  },
  "iterator": {
    "type": "bucket",
    "sorting_keys": [["tokens", "num_tokens"]],
    "batch_size" : 80
  },

  "trainer": {
    "num_epochs": 500,
    "grad_clipping": 1.0,
    "patience": 20,
    "validation_metric": "+f1-measure-overall",
    "cuda_device": 0,
    "optimizer": {
      "type": "adadelta",
      "rho": 0.95
    }
  }
}
```

Hope that helps!

**Comment by mdelhoneux** [comment]
Thanks a lot! This does seem to work for me as well. And my bad about the recursion depth error, I had reverted the version with a git reset but forgot to re-install allennlp...

**Comment by DeNeutoy** [comment]
@nelson-liu can we merge this soon? One thing before we do:
1. Remove the coref config with elmo, it doesn't work in allennlp.

@matt-peters any more comments here? Perhaps we should have these configs in a specific place rather than cluttered around the main training configs?

**Comment by nelson-liu** [comment]
I know @matt-peters was working on this yesterday. One thing he mentioned is that it'd be good to fix the issues in the SRL model -- i took a cursory look at this yesterday (not familiar with C or CUDA, sorry), and made some observations that i posted in #1626 

We should also mention the part about how the SRL metric doesn't quite track with the conlleval metric...

**Comment by matt-peters** [comment]
@DeNeutoy @nelson-liu  All of the essential details should be here. I approved the PR, but will hold off on merging until tomorrow if someone wants to add additional comments.

**Pull request merged**
