### PR TITLE
allow TextFieldEmbedder to have EmptyEmbedder that may not be in input

### PR DESCRIPTION
**Pull request by tpanza**
Additional patch for #4554

### CODE REVIEW

**Comment by tpanza** [comment]
@dirkgr can you please take a look

**Comment by epwalsh** [comment]
Hey @tpanza, Dirk is currently out but will be back next week, so this may have to wait until then.

**Review by dirkgr — APPROVED** [review]
I could have sworn I made this exact change already.

Anyways, I'm not wild about giving `EmptyEmbedder` special treatment all over, but it's the lesser of the evils, compared to re-jiggering the API to allow for the empty case more cleanly.

**Comment by dirkgr** [comment]
@tpanza, is this the last of the issues? Can you now re-train ELMo and use it as an embedder?

**Comment by tpanza** [comment]
> 
> 
> @tpanza, is this the last of the issues? Can you now re-train ELMo and use it as an embedder?

Hi @dirkgr. Yes! What would be the best place to document steps with a dummy/toy example? In other words, what would be the best place to make an updated version of [this tutorial](https://github.com/allenai/allennlp/blob/v0.9.0/tutorials/how_to/training_transformer_elmo.md)?

**Comment by dirkgr** [comment]
The new place for that kind of stuff is at https://github.com/allenai/allennlp-guide. That ultimately gets published here: https://guide.allennlp.org. You still write Markdown, but the layout engine makes that fancy website out of it. I'd love it if you could add a chapter on this!

**Pull request merged**
