### PR TITLE
use wordsplit with taggers

### PR DESCRIPTION
**Pull request by WrRan**
patch to #1929

### CODE REVIEW

**Comment by matt-gardner** [comment]
Ok, it took me a while, but I understand both issues.  The first one is that we are not consistent in how we are checking for missing / empty values between `count_vocab_items` and `tokens_to_indices`.  The second one is that if you don't have OOV / padding tokens in your vocabulary for one of your token tensors, our masking logic is incorrect.

For issue 1, I still don't understand the case where this might _actually_ be a problem, and whether this fix does the right thing.  E.g., when do you get `''` for a POS or NER tag?  Is replacing with `NONE` really the right thing?  I don't know without seeing an example.  If you could add a test case that fails before your change (preferably with actual input that your code failed on), that would help.

For issue 2, I don't think your fix actually solves the underlying problem.  What if I _only_ have NER tags (or things that don't have OOV / padding tokens) for my indexer?  Then I still get the wrong result.  The issue is that the mask code assumes you have these tokens, and I don't know of a way around it.  I think the right solution here is to just make sure the vocabulary namespace that you use for each of your token indexers is padded.  We can't recover from the case where you don't have padding tokens, but still want to compute a mask.

**Comment by matt-gardner** [comment]
Ok, thanks, I didn't know that that was spacy's behavior for "no NER tag".  A failing test before this change would still be good to have, just to make sure we don't break it later.

For the latter issue, I don't know of an easy way around this.  We'd have to have the `TokenIndexer` check that the `Vocabulary` thinks the namespace it's using should be padded, and that's a pretty ugly check.  The default namespace would have given you padding tokens - did you change something to get this error?

**Comment by WrRan** [comment]
Actually, `Vocabulary` does not pad tokens with namespace ending with `tags` or `labels`.
https://github.com/allenai/allennlp/blob/043ff07c6f0e0f95b71fe3463f86b722f871a6ad/allennlp/data/vocabulary.py#L22
https://github.com/allenai/allennlp/blob/043ff07c6f0e0f95b71fe3463f86b722f871a6ad/allennlp/data/vocabulary.py#L282-L283

Moreover, the default namespaces of PosTagIndexer and NerTagIndexer are `pos_tags` and `ner_tags` respectively.
So I got this error when changing nothing but configuration.

**Comment by matt-gardner** [comment]
Oh, sorry, you're right. We should change that default.

**Comment by WrRan** [comment]
Happy to be right. :)

**Comment by matt-gardner** [comment]
Ok, so what this PR needs in order to be merged:

1. Remove the changes to `util.py`.
2. Add a test case to catch the problem with blank NER / POS tags.
3. Change the default namespace for the NER and POS token indexers to not end in `tags`.

**Comment by WrRan** [comment]
Got it.
But may it be a good idea to modify `DEFAULT_NON_PADDED_NAMESPACES` in `vocabulary.py` instead of the default namespaces for the NER and POS?

**Comment by matt-gardner** [comment]
No, we don't want to modify the defaults in the vocabulary, because (1) the main use case for those defaults is for things you're predicting (i.e., when POS or NER tags are used in a `SequenceLabelField` as your target), and (2) we don't want to make changes that break existing code.  I suspect very few people are using these particular `TokenIndexers`, and if they are they would have run into this issue, anyway, because it's just broken.  So the right place to fix this is in the `TokenIndexers`.

**Comment by WrRan** [comment]
Yes, I see. You are right.

**Comment by WrRan** [comment]
Sorry.
I have deleted original repo, which makes this PR from `unknown repo`.
And I do not know how to handle this.
So I create a new PR #1981, this one may be closed.

**Pull request closed without merging**
