### PR TITLE
Adding DatasetReader for the bAbI tasks and Qangaroo

### PR DESCRIPTION
**Pull request by nicola-decao**
Hi,

I would like to add a DatasetReader for the bAbI tasks and Qangaroo.
The bAbI reader considers the format used here https://github.com/facebook/bAbI-tasks, therefore, the official one. The Qangaroo reader takes JSON from here http://qangaroo.cs.ucl.ac.uk.

### CODE REVIEW

**Comment by matt-gardner** [comment]
Thanks for the PR!  In order for us to merge this, though, it needs to have tests.  You can look at the other dataset readers to see what tests we have for them.  There are also some style and type problems that TeamCity is bringing up, which you can see [here](http://build.allennlp.org/viewLog.html?buildId=8883&buildTypeId=AllenNLP_AllenNLPPullRequests&tab=buildLog).

**Comment by nicola-decao** [comment]
Cool! Thanks for the advice. I am fixing the issues and writing the tests.

**Comment by nicola-decao** [comment]
Hi, I added test and corrected all the type checking.

The only 2 warnings that I cannot fix are:
```
[18:36:53][Step 4/10] ************* Module allennlp.data.dataset_readers.babi
[18:36:53][Step 4/10] W: 72, 4: Parameters differ from overridden 'text_to_instance' method (arguments-differ)
[18:36:53][Step 4/10] ************* Module allennlp.data.dataset_readers.reading_comprehension.qangaroo
[18:36:53][Step 4/10] W: 65, 4: Parameters differ from overridden 'text_to_instance' method (arguments-differ)
```

I don't know why since it seems the same as other `DataReader` classes.

Can you help?

**Comment by matt-gardner** [comment]
We ignore those warnings: https://github.com/allenai/allennlp/blob/0663762960a4522d4740eea460f63a06eeba126d/allennlp/data/dataset_readers/event2mind.py#L175

**Comment by matt-gardner** [comment]
Thanks @nicola-decao!

**Comment by nicola-decao** [comment]
I'm glad to contribute :slightly_smiling_face:

**Pull request merged**
