### PR TITLE
Fix bug for RNNs for AutoRegressiveSeqDecoder

### PR DESCRIPTION
**Pull request by nicola-decao**
This function https://github.com/allenai/allennlp/blob/e0f573a4d3a3ecbc1b0e10dd7fd7f48f6269e744/allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py#L408
updates the `state` dictionary and during the evaluation, it breaks the prediction in https://github.com/allenai/allennlp/blob/e0f573a4d3a3ecbc1b0e10dd7fd7f48f6269e744/allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py#L413
since the `hidden_state` and the target sequence tensors are not re-initialized. This is a bug.

I changed the behaviour during evaluation providing a deep copy of the state such that the state forwarded to `self._forward_loss` and `self._forward_beam_search` are the same.

### CODE REVIEW

**Comment by nicola-decao** [comment]
@matt-gardner there is a problem in the master branch. Both my pull request, https://github.com/allenai/allennlp/pull/3461, and https://github.com/allenai/allennlp/pull/3453 fails the same test but seems not correlated.

**Comment by schmmd** [comment]
Given that #3433 is merged can we close this PR @nicola-decao ?

**Comment by nicola-decao** [comment]
> Given that #3433 is merged can we close this PR @nicola-decao ?

No, this is a different bug.

**Comment by schmmd** [comment]
The build error seems very related to this change as it relates to `deepcopy` (`RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment`).

```
[09:49:14][Step 4/11] =================================== FAILURES ===================================
[09:49:14][Step 4/11] _____ ComposedSeq2SeqTest.test_bidirectional_model_can_train_save_and_load _____
[09:49:14][Step 4/11] 
[09:49:14][Step 4/11] self = <allennlp.tests.models.encoder_decoders.composed_seq2seq_test.ComposedSeq2SeqTest testMethod=test_bidirectional_model_can_train_save_and_load>
[09:49:14][Step 4/11] 
[09:49:14][Step 4/11]     def test_bidirectional_model_can_train_save_and_load(self):
[09:49:14][Step 4/11]     
[09:49:14][Step 4/11]         param_overrides = json.dumps(
[09:49:14][Step 4/11]             {
[09:49:14][Step 4/11]                 "model": {
[09:49:14][Step 4/11]                     "encoder": {"bidirectional": True},
[09:49:14][Step 4/11]                     "decoder": {"decoder_net": {"decoding_dim": 20, "bidirectional_input": True}},
[09:49:14][Step 4/11]                 }
[09:49:14][Step 4/11]             }
[09:49:14][Step 4/11]         )
[09:49:14][Step 4/11]         self.ensure_model_can_train_save_and_load(
[09:49:14][Step 4/11] >           self.param_file, tolerance=1e-2, overrides=param_overrides
[09:49:14][Step 4/11]         )
[09:49:14][Step 4/11] 
[09:49:14][Step 4/11] allennlp/tests/models/encoder_decoders/composed_seq2seq_test.py:28: 
[09:49:14][Step 4/11] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[09:49:14][Step 4/11] allennlp/common/testing/model_test_case.py:116: in ensure_model_can_train_save_and_load
[09:49:14][Step 4/11]     model, model_batch, gradients_to_ignore, disable_dropout
[09:49:14][Step 4/11] allennlp/common/testing/model_test_case.py:196: in check_model_computes_gradients_correctly
[09:49:14][Step 4/11]     result = model(**model_batch)
[09:49:14][Step 4/11] /usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py:541: in __call__
[09:49:14][Step 4/11]     result = self.forward(*input, **kwargs)
[09:49:14][Step 4/11] allennlp/models/encoder_decoders/composed_seq2seq.py:122: in forward
[09:49:14][Step 4/11]     return self._decoder(state, target_tokens)
[09:49:14][Step 4/11] /usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py:541: in __call__
[09:49:14][Step 4/11]     result = self.forward(*input, **kwargs)
[09:49:14][Step 4/11] allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py:409: in forward
[09:49:14][Step 4/11]     state_forward_loss = state if self.training else deepcopy(state)
[09:49:14][Step 4/11] /usr/local/lib/python3.6/copy.py:150: in deepcopy
[09:49:14][Step 4/11]     y = copier(x, memo)
[09:49:14][Step 4/11] /usr/local/lib/python3.6/copy.py:240: in _deepcopy_dict
[09:49:14][Step 4/11]     y[deepcopy(key, memo)] = deepcopy(value, memo)
[09:49:14][Step 4/11] /usr/local/lib/python3.6/copy.py:161: in deepcopy
[09:49:14][Step 4/11]     y = copier(memo)
[09:49:14][Step 4/11] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[09:49:14][Step 4/11] 
[09:49:14][Step 4/11] self = tensor([[[ 0.0165,  0.1751,  0.0750,  0.0251, -0.0666, -0.0823, -0.0995,
[09:49:14][Step 4/11]           -0.0348,  0.0137, -0.0228, -0.0769,...0426,  0.0202,
[09:49:14][Step 4/11]           -0.0185, -0.1465, -0.0188,  0.1207,  0.2299, -0.0562]]],
[09:49:14][Step 4/11]        grad_fn=<IndexSelectBackward>)
[09:49:14][Step 4/11] memo = {139648236713736: {'source_mask': tensor([[1, 1, 1, 1, 1, 0, 0, 0],
[09:49:14][Step 4/11]         [1, 1, 1, 1, 1, 1, 0, 0],
[09:49:14][Step 4/11]         [1, 1, 1...648236632680: [tensor([[1, 1, 1, 1, 1, 0, 0, 0],
[09:49:14][Step 4/11]         [1, 1, 1, 1, 1, 1, 0, 0],
[09:49:14][Step 4/11]         [1, 1, 1, 1, 1, 1, 1, 1]])]}
[09:49:14][Step 4/11] 
[09:49:14][Step 4/11]     def __deepcopy__(self, memo):
[09:49:14][Step 4/11]         if not self.is_leaf:
[09:49:14][Step 4/11] >           raise RuntimeError("Only Tensors created explicitly by the user "
[09:49:14][Step 4/11]                                "(graph leaves) support the deepcopy protocol at the moment")
[09:49:14][Step 4/11] E           RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

**Comment by dirkgr** [comment]
What is the state of this? Is it ready to go, except for the formatting changes?

**Comment by nicola-decao** [comment]
> What is the state of this? Is it ready to go, except for the formatting changes?

Yes exactly. I'm fixing it now.

**Comment by nicola-decao** [comment]
@schmmd @dirkgr  I fixed formatting, it shoud be ready to go.

**Comment by dirkgr** [comment]
Thank you @nicola-decao!

**Pull request merged**
