### PR TITLE
Implements TensorCache in terms of HDF5, not LMDB

### PR DESCRIPTION
**Pull request by dirkgr**
@AkshitaB, @epwalsh, you have both asked about this.

### CODE REVIEW

**Review by AkshitaB — CHANGES_REQUESTED** [review]
Oh, I basically had this much for my version, but ran into some issues in the multi gpu setting, where it complained about the file not being closed (and being closed, on a different run :/ ). I worked around it for my use-case by never writing to the cache, and by registering an atexit method externally, since `__del__` didn't seem to do the trick. 

We should add a test for the distributed setting.

**Comment by epwalsh** [comment]
I don't have a lot of context here. Why did we decide to switch in the first place?

**Comment by dirkgr** [comment]
LMDB has occasional errors that are hard to debug. Also, HDF5 ought to be faster, and takes less code. HDF5 would have been the right choice from the start (but we have to make sure the multi-GPU case works).

**Comment by dirkgr** [comment]
This is not going to work. In the distributed scenario, h5py falls apart. There is a way to run "parallel h5py", but it's too difficult to install and configure.

**Pull request closed without merging**
