### PR TITLE
Remove obsolete rm since we upgraded to Pytorch 0.2.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
@joelgrus are you able to give me instructions on how to reproduce the `GOMP_4.0 not found` error?  Regardless, I'm pretty sure this change is needed.

**Comment by schmmd** [comment]
I'm able to build a Docker image and pass all tests with this change.

**Comment by joelgrus** [comment]
it's there because I ran into this problem: https://github.com/hughperkins/pytorch/issues/28

but if it works in the new version, it works.

**Comment by schmmd** [comment]
@joelgrus @DeNeutoy that file actually no longer exists, and so the `rm` command was failing the Docker build.  That's how I found it.

I saw the GitHub issue already.  I just wasn't sure how you repro-ed.

**Comment by joelgrus** [comment]
I originally added that in because my docker builds were failing without it, which is what led me to the issue.

**Comment by schmmd** [comment]
Huh, that seems surprising as it's near the end of the Dockerfile.  In any case, we're up and running again now that this is merged.  https://cloud.docker.com/swarm/allennlp/repository/docker/allennlp/allennlp-gpu/tags

**Pull request merged**
