### PR TITLE
Makes the `evaluate` command work for the multitask case

### LINKED ISSUE #5537: Using evaluate command for multi-task model
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description
evaluate command can not support multitask that input_file only takes the file name as input.
But multi-task reader needs Dic.

<details>
<summary><b>Python traceback:</b></summary>
<p>

(allennlp2_8) D:\WorkSpace\GeoQA-with-UniT -2_8>allennlp evaluate save/test test_data_path --include-package NGS_Aux --cuda-device 0
2022-01-07 09:38:22,837 - INFO - allennlp.models.archival - loading archive file save/test
2022-01-07 09:38:23,469 - INFO - allennlp.data.vocabulary - Loading token dictionary from save/test\vocabulary.
##### Checkpoint Loaded! #####
2022-01-07 09:38:28,271 - INFO - allennlp.modules.token_embedders.embedding - Loading a model trained before embedding extension was implemented; pass an explicit vocab namespace if you wan
t to extend the vocabulary.
2022-01-07 09:38:29,051 - INFO - allennlp.common.checks - Pytorch version: 1.10.0+cu113
2022-01-07 09:38:29,053 - INFO - allennlp.commands.evaluate - Reading evaluation data from test_data_path
Traceback (most recent call last):
  File "D:\Anaconda\envs\allennlp2_8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\allennlp2_8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\allennlp2_8\Scripts\allennlp.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda\envs\allennlp2_8\lib\site-packages\allennlp\__main__.py", line 46, in run
    main(prog="allennlp")
  File "D:\Anaconda\envs\allennlp2_8\lib\site-packages\allennlp\commands\__init__.py", line 123, in main
    args.func(args)
  File "D:\Anaconda\envs\allennlp2_8\lib\site-packages\allennlp\commands\evaluate.py", line 189, in evaluate_from_args
    params=data_loader_params, reader=dataset_reader, data_path=evaluation_data_path
  File "D:\Anaconda\envs\allennlp2_8\lib\site-packages\allennlp\common\from_params.py", line 656, in from_params
    **extras,
  File "D:\Anaconda\envs\allennlp2_8\lib\site-packages\allennlp\common\from_params.py", line 686, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "D:\Anaconda\envs\allennlp2_8\lib\site-packages\allennlp\data\data_loaders\multitask_data_loader.py", line 143, in __init__
    if self.readers.keys() != self.data_paths.keys():
AttributeError: 'str' object has no attribute 'keys'

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

Windows:
aiohttp                  3.8.0
aiosignal                1.2.0
allennlp                 2.8.0
argcomplete              1.12.3
argon2-cffi              21.1.0
async-timeout            4.0.0
asynctest                0.13.0
atomicwrites             1.4.0
attrs                    21.2.0
backcall                 0.2.0
backports.csv            1.0.7
base58                   2.1.1
beautifulsoup4           4.10.0
bleach                   4.1.0
blis                     0.7.5
boto3                    1.19.12
botocore                 1.22.12
cached-path              0.3.2
cached-property          1.5.2
cachetools               4.2.4
catalogue                1.0.0
certifi                  2021.10.8
cffi                     1.15.0
chardet                  4.0.0
charset-normalizer       2.0.7
checklist                0.0.11
cheroot                  8.5.2
CherryPy                 18.6.1
click                    8.0.3
colorama                 0.4.4
configparser             5.1.0
cryptography             35.0.0
cymem                    2.0.6
Cython                   0.29.23
datasets                 1.15.1
debugpy                  1.5.1
decorator                5.1.0
defusedxml               0.7.1
dill                     0.3.4
docker-pycreds           0.4.0
en-core-web-sm           2.3.0
entrypoints              0.3
fairscale                0.4.0
feedparser               6.0.8
filelock                 3.3.2
frozenlist               1.2.0
fsspec                   2021.11.0
future                   0.18.2
gensim                   4.1.2
gitdb                    4.0.9
GitPython                3.1.24
google-api-core          2.2.2
google-auth              2.3.3
google-cloud-core        2.1.0
google-cloud-storage     1.42.3
google-crc32c            1.3.0
google-resumable-media   2.1.0
googleapis-common-protos 1.53.0
h5py                     3.5.0
huggingface-hub          0.1.1
idna                     3.3
importlib-metadata       4.8.1
importlib-resources      5.4.0
iniconfig                1.1.1
ipykernel                6.5.0
ipython                  7.29.0
ipython-genutils         0.2.0
ipywidgets               7.6.5
iso-639                  0.4.5
jaraco.classes           3.2.1
jaraco.collections       3.4.0
jaraco.functools         3.4.0
jaraco.text              3.6.0
jedi                     0.18.0
jieba                    0.42.1
Jinja2                   3.0.2
jmespath                 0.10.0
joblib                   1.1.0
jsonschema               4.2.1
jupyter                  1.0.0
jupyter-client           7.0.6
jupyter-console          6.4.0
jupyter-core             4.9.1
jupyterlab-pygments      0.1.2
jupyterlab-widgets       1.0.2
lmdb                     1.2.1
lxml                     4.6.4
MarkupSafe               2.0.1
matplotlib-inline        0.1.3
mistune                  0.8.4
more-itertools           8.10.0
multidict                5.2.0
multiprocess             0.70.12.2
munch                    2.5.0
murmurhash               1.0.6
nbclient                 0.5.4
nbconvert                6.2.0
nbformat                 5.1.3
nest-asyncio             1.5.1
nltk                     3.6.5
notebook                 6.4.5
numpy                    1.21.4
opencv-python            4.5.4.58
overrides                3.1.0
packaging                21.2
pandas                   1.3.4
pandocfilters            1.5.0
parso                    0.8.2
pathtools                0.1.2
pathy                    0.6.1
patternfork-nosql        3.6
pdfminer.six             20211012
pickleshare              0.7.5
Pillow                   8.4.0
pip                      21.2.4
plac                     1.1.3
pluggy                   1.0.0
portend                  3.0.0
preshed                  3.0.6
prometheus-client        0.12.0
promise                  2.3
prompt-toolkit           3.0.22
protobuf                 3.19.1
psutil                   5.8.0
py                       1.11.0
pyarrow                  6.0.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.21
pydantic                 1.8.2
Pygments                 2.10.0
pyparsing                2.4.7
pyrsistent               0.18.0
pytest                   6.2.5
python-dateutil          2.8.2
python-docx              0.8.11
pytz                     2021.3
pywin32                  302
pywinpty                 1.1.5
PyYAML                   6.0
pyzmq                    22.3.0
qtconsole                5.1.1
QtPy                     1.11.2
regex                    2021.11.2
requests                 2.26.0
rsa                      4.7.2
s3transfer               0.5.0
sacremoses               0.0.46
scikit-learn             1.0.1
scipy                    1.7.2
Send2Trash               1.8.0
sentencepiece            0.1.96
sentry-sdk               1.4.3
setuptools               58.0.4
sgmllib3k                1.0.0
shortuuid                1.0.1
six                      1.16.0
smart-open               5.2.1
smmap                    5.0.0
soupsieve                2.3
spacy                    2.3.7
spacy-legacy             3.0.8
sqlitedict               1.7.0
srsly                    1.0.5
subprocess32             3.5.4
tempora                  4.1.2
tensorboardX             2.4
termcolor                1.1.0
terminado                0.12.1
testpath                 0.5.0
thinc                    7.4.5
threadpoolctl            3.0.0
tokenizers               0.10.3
toml                     0.10.2
torch                    1.10.0+cu113
torchaudio               0.10.0+cu113
torchvision              0.11.1+cu113
tornado                  6.1
tqdm                     4.62.3
traitlets                5.1.1
transformers             4.12.3
typer                    0.4.0
typing-extensions        3.10.0.2
urllib3                  1.26.7
wandb                    0.12.6
wasabi                   0.8.2
wcwidth                  0.2.5
webencodings             0.5.1
wheel                    0.37.0
widgetsnbextension       3.5.2
wincertstore             0.2
xxhash                   2.0.2
yarl                     1.7.2
yaspin                   2.1.0
zc.lockfile              2.0
zipp                     3.6.0

Python version:
3.7
<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

### PR DESCRIPTION
**Pull request by dirkgr**
Fixes #5537.

### CODE REVIEW

**Review by AkshitaB — COMMENTED** [review]
Looks fine. Will there be a need to have the output files and the prediction output files in json format as well?

**Comment by dirkgr** [comment]
`evaluate` just produces metrics, right? The metrics are prefixed with the head name. So no, not in this case. Maybe we'll need that for `predict`? Or maybe that's already solved? I don't remember.

**Comment by AkshitaB** [comment]
> `evaluate` just produces metrics, right? The metrics are prefixed with the head name. So no, not in this case. Maybe we'll need that for `predict`? Or maybe that's already solved? I don't remember.

The evaluate command also optionally takes `predictions_output_file` https://github.com/allenai/allennlp/blob/dbdfc599ab844714ed3cd34673d831aef1ff0daa/allennlp/commands/evaluate.py#L55 .

And the list of output files is supposed to match the list of input files for metrics too.

**Comment by dirkgr** [comment]
I added this to the test, and it works.

**Comment by dirkgr** [comment]
Closing in favor of #5579.

**Pull request closed without merging**
