### PR TITLE
Fix chdir in ModelTestCase breaking downstream models

### PR DESCRIPTION
**Pull request by nelson-liu**
ModelTestCase has a few `chdir`s since after we moved the tests into the module, all the relative paths in the test fixtures were broken (since they assumed that we were running the tests in the same directory as the `tests` folder). I got around this by using `os.chdir`, but did not realize that this would break models that import and use `ModelTestCase` (see #1417 ).

I think a reasonable solution to this is to simply remove all the `chdir` calls and add a symbolic link in the project root called `tests` that links to the tests folder (in the module root). This means that the relative paths in the fixtures don't need to be redone and downstream clients using `ModelTestCase` won't deal with issues from `os.chdir`.

### CODE REVIEW

**Comment by nelson-liu** [comment]
for the future: perhaps it'd be good to rerun and update https://github.com/allenai/allennlp-as-a-library-example as part of the process of testing a new release, to ensure that nothing breaks terribly for folks using allennlp as a library.

**Comment by joelgrus** [comment]
I'm not a huge fan of this solution.

can't `ModelTestCase` just add `self.PROJECT_ROOT` to `sys.path`? would that fix things? or am I misunderstanding the issue

**Comment by nelson-liu** [comment]
No, it wouldn’t. The fixtures themselves define relative paths to data, which get broken. It’s unrelated to PYTHONPATH

**Comment by joelgrus** [comment]
as discussed offline, I think just correcting the paths in the test fixtures is a better solution

**Pull request merged**
