### PR TITLE
Add ability to specify the embedding layer if the model does not use `TextFieldEmbedder`

### PR DESCRIPTION
**Pull request by AkshitaB**
Fixes https://github.com/allenai/allennlp/issues/4790

### CODE REVIEW

**Review by dirkgr — COMMENTED** [review]
Controversial opinion: Why don't we put `get_embedding_layer()` on the model instead of on the predictor, with the default implementation we already have? It would be pretty trivial to return the correct layer from the model most of the time, and it gives us the option of keeping predictors more general.

What do you think of changing the name at the same time? I struggle to come up with something more [wieldy](https://english.stackexchange.com/questions/129391/how-did-wieldy-the-positive-form-of-unwieldy-come-to-be-a-non-existent-wor) than `get_interpretable_input_layer()`.

**Comment by AkshitaB** [comment]
> Controversial opinion: Why don't we put `get_embedding_layer()` on the model instead of on the predictor, with the default implementation we already have? It would be pretty trivial to return the correct layer from the model most of the time, and it gives us the option of keeping predictors more general.

The advantage with keeping it in Predictor is that you can then wrap a predictor around a non-AllenNLP model and use the interpreters. That was the original use case.

> 
> What do you think of changing the name at the same time? I struggle to come up with something more [wieldy](https://english.stackexchange.com/questions/129391/how-did-wieldy-the-positive-form-of-unwieldy-come-to-be-a-non-existent-wor) than `get_interpretable_input_layer()`.

Can't think of a better name off the top of my head. Perhaps it makes sense to add the need for the method in the docstring? That this is required for interpret code?

**Comment by dirkgr** [comment]
> The advantage with keeping it in Predictor is that you can then wrap a predictor around a non-AllenNLP model and use the interpreters. That was the original use case.

Fair enough. I think I'd love to have both, where `Predictor` by default defers to the `Model`, but it can do something else if needed. But let's not overload this PR.

**Review by dirkgr — APPROVED** [review]
Looks good, but I'd really like to change those names. Can we make them `get_interpretable_layer()` and `get_interpretable_text_field_embedder()`? I know those names are long, but for the vision models, the layer you would want is already not really an embedding layer.

**Comment by AkshitaB** [comment]
> Looks good, but I'd really like to change those names. Can we make them `get_interpretable_layer()` and `get_interpretable_text_field_embedder()`? I know those names are long, but for the vision models, the layer you would want is already not really an embedding layer.

@dirkgr Done. The names are changed.

**Pull request merged**
