### PR TITLE
Remove upper bounds for dependencies in `requirements.txt`

### LINKED ISSUE #5728: Remove upper bounds for requirements
**Is your feature request related to a problem? Please describe.**

Remove upper bounds for dependencies in `requirements.txt`, where possible

**Describe the solution you'd like**

I would like the upper bounds for versions in `requirements.txt` to removed except for cases that are known to be broken. In #4324, the stated reason for this pinning was to prevent CI breakage. It also stated that you had a bot to upgrade dependencies automatically. However, now that the library is being retired and Depdendabot was disabled in 20df7cdd3eea7f895ceee9c57e2be1a843510748, this upgrade process is no longer happening.

I would like to keep using this library, at least for a little while, and removing these upper bounds would make that much easier. I feel that the circumstances mean the original reasons might not apply and that the topic should be reconsidered. To prevent CI breakage after upper bound removal, they can be kept in a [constraints file](https://pip.pypa.io/en/stable/user_guide/#constraints-files) for use in CI. It would be up to end users in the future to limit dependency conflicts if they encounter any.

I understand if you don't want to go through the effort for this, but I can create a PR if this idea is approved.

**Describe alternatives you've considered**

I've considered forking this library and applying a patch so I can upgrade `spacy`:

```diff
diff --git a/requirements.txt b/requirements.txt
index a9514301d70..c2bbe742460 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -7,7 +7,7 @@ cached-path>=1.1.3,<1.2.0
 fairscale==0.4.6
 jsonnet>=0.10.0 ; sys.platform != 'win32'
 nltk>=3.6.5
-spacy>=2.1.0,<3.4
+spacy>=2.1.0,<3.5
 numpy>=1.21.4
 tensorboardX>=1.2
 requests>=2.28
```

However, everyone would need to maintain their own forks, which seems inefficient. Doing this centrally would save work overall and allow the library to be more usable after its official retirement.

### PR DESCRIPTION
**Pull request by aphedges**
Closes #5728.

Changes proposed in this pull request:
- Remove upper bounds for dependencies in `requirements.txt`

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [x] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.
- [ ] **`codecov/patch`** reports high test coverage (at least 90%).
    You can find this under the "Actions" tab of the pull request once the other checks have finished.

---

The stated reason for this pinning was to prevent CI breakage, and there was a bot to help upgrade dependencies automatically. However, now that the library is being retired and Depdendabot was, this upgrade process is no longer happening.

Removing these upper bounds will make using the library in the future much easier. To prevent CI breakage after upper bound removal, they can be kept in a constraints file for use in CI. It would be up to end users in the future to limit dependency conflicts if they encounter any.

I have checked the history, and as far as I can tell, none of these upper pins exist to prevent a known breakage. Therefore, I moved them all to the constraints file.

### CODE REVIEW

**Comment by aphedges** [comment]
@epwalsh, I have created a PR. You mentioned in <https://github.com/allenai/allennlp/issues/5728#issuecomment-1314351630> that you would review it.

Because some of the changes I made are to CI itself, I can't properly test this locally. I'd appreciate if you could approve the GitHub Actions workflows.

**Comment by aphedges** [comment]
I see there are some failing tests. I'll investigate and see if I can fix the problem.

**Comment by aphedges** [comment]
It turns out that I missed using the constraints file in several places. The most difficult was to get it working properly with `pip-compile`, but <https://github.com/jazzband/pip-tools/issues/1551> fortunately explained how to do so.

**Review by epwalsh — APPROVED** [review]
This is great, thank you @aphedges!

**Pull request merged**
