### PR TITLE
Remove deprecated SpanPruner

### PR DESCRIPTION
**Pull request by nelson-liu**

### CODE REVIEW

**Comment by nelson-liu** [comment]
hold off on merging this, was trying to verify that the code snippet in the tutorial still works and ran into #2250 . Would be good to figure out what's going on there first.

**Comment by matt-gardner** [comment]
Did #2257 actually fix #2250?  Is this ready for review?

**Comment by nelson-liu** [comment]
This is good to go now @matt-gardner , i wanted to make sure that the code snippet in the tutorial still ran properly (and it was indeed outdated).

**Comment by nelson-liu** [comment]
And yes, #2257 actually fixes #2250

**Pull request merged**
