### PR TITLE
Add allennlp test-install command

### LINKED ISSUE #856: create an easy way for people to test that their pip install is working correctly and that they've got all the right dependencies and downloads
possibly something as simple as adding a

```
python -m allennlp.run test-install
```

command or something

### PR DESCRIPTION
**Pull request by nelson-liu**
Fixes #856 by creating an `allennlp test-install` command that runs the unit test suite. 

I've tested it locally outside of my allennlp install directory and it seems to work fine for both options, but unsure how to write a unit test for this.

This command skips the sniff tests by default, which should address @DeNeutoy 's concern from #1208 ?

### CODE REVIEW

**Comment by DeNeutoy** [comment]
Yeah, I don't think we can test the thing which runs the tests in the tests 😆 

Once we set up CI which runs the pip installation, this will be tested implicitly by that, so I think we're all good.

**Comment by nelson-liu** [comment]
I realized that if the `test_requirements` (pytest, flaky, responses>=0.7, jupyter) are not installed, this will totally break all of the `allennlp` commands.

Is it worth adding these packages to the requirements installed by pip? Alternatively, we could fix https://github.com/allenai/allennlp/issues/1200 ...

**Comment by matt-gardner** [comment]
The whole reason `requirements.txt` was separate from `test_requirements.txt` was because we weren't including the tests in the pip release.  If we're going to include tests in the pip release, do we need that distinction anymore?

**Comment by nelson-liu** [comment]
perhaps we can move these essential testing packages (pytest, flaky, responses>=0.7, jupyter) to requirements.txt and the setup.py `install_requires`, then rename `requirements_test.txt` to `requirements_dev.txt`? 

no need for a user to install sphinx or numpydoc or coverage...

**Comment by matt-gardner** [comment]
I think others have stronger / more informed opinions here than me, so I'll let someone else answer the question.  I was just providing some context.

**Comment by schmmd** [comment]
Jupyter is enormous and is currently in our `test_requirements`.  I'd rather not have that in our `requirements.txt`--but at the same time it'd be great to eliminate `test_requirements` so I'm not sure what's best!

**Comment by nelson-liu** [comment]
another option is to turn off notebook tests by default in `test-install` and make users install jupyter in order to run them.

**Comment by joelgrus** [comment]
ANOTHER option is to rewrite the notebook tutorials as markdown tutorials and get rid of our jupyter dependency altogether 😇

**Comment by DeNeutoy** [comment]
@nelson-liu Either solution you propose is fine - we can re-write the tutorials in a separate PR

**Pull request merged**
