### PR TITLE
Add Sphinx support for generating HTML documentation.

### PR DESCRIPTION
**Pull request by schmmd**
I took a stab one how to organize our documentation.  I started with `sphinx-apidoc` and then amended the output.  I have no concerns if the organization changes.

### CODE REVIEW

**Comment by schmmd** [comment]
I still have some outstanding errors.  I'm hopeful someone else will be able to more immediately identify the problems.

```
$ make clean                                                                                                                                                                                                                                (nlp) 
Removing everything under 'build'...
$ make html                                                                                                                                                                                                                                   (nlp) 
Running Sphinx v1.5.3
making output directory...
/Users/michael/hack/allenai/allennlp
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 23 source files that are out of date
updating environment: 23 added, 0 changed, 0 removed
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 64527.75it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 33621.68it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 60567.57it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 38836.15it/s]
/Users/michael/miniconda3/envs/nlp/lib/python3.5/site-packages/numpydoc/docscrape.py:139: UserWarning: Unknown section Return                                                                                                                                       
  warn("Unknown section %s" % key)
/Users/michael/miniconda3/envs/nlp/lib/python3.5/site-packages/numpydoc/docscrape.py:139: UserWarning: Unknown section Return                                                                                                                                       
  warn("Unknown section %s" % key)
/Users/michael/miniconda3/envs/nlp/lib/python3.5/site-packages/numpydoc/docscrape.py:139: UserWarning: Unknown section Return                                                                                                                                       
  warn("Unknown section %s" % key)
reading sources... [100%] index                                                                                                                                                                                                                                     
/Users/michael/hack/allenai/allennlp/allennlp/data/vocabulary.py:docstring of allennlp.data.vocabulary.Vocabulary:37: WARNING: Inline emphasis start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/data/vocabulary.py:docstring of allennlp.data.vocabulary.Vocabulary:37: WARNING: Inline emphasis start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/data/vocabulary.py:docstring of allennlp.data.vocabulary.Vocabulary.from_files:20: WARNING: Inline literal start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/data/dataset_readers/semantic_role_labelling.py:docstring of allennlp.data.dataset_readers.semantic_role_labelling.SrlReader:37: ERROR: Unexpected indentation.
/Users/michael/hack/allenai/allennlp/allennlp/data/dataset_readers/squad.py:docstring of allennlp.data.dataset_readers.squad.SquadSentenceSelectionReader:4: WARNING: Inline literal start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/data/dataset_readers/squad.py:docstring of allennlp.data.dataset_readers.squad.SquadSentenceSelectionReader:39: WARNING: Inline literal start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/data/fields/tag_field.py:docstring of allennlp.data.fields.tag_field.TagField:21: WARNING: Inline literal start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/data/iterators/bucket_iterator.py:docstring of allennlp.data.iterators.bucket_iterator.BucketIterator:19: ERROR: Unexpected indentation.
/Users/michael/hack/allenai/allennlp/allennlp/data/iterators/bucket_iterator.py:docstring of allennlp.data.iterators.bucket_iterator.BucketIterator:16: WARNING: Inline literal start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/data/iterators/adaptive_iterator.py:docstring of allennlp.data.iterators.adaptive_iterator.AdaptiveIterator:13: ERROR: Undefined substitution referenced: "sentence1".
/Users/michael/hack/allenai/allennlp/allennlp/data/iterators/adaptive_iterator.py:docstring of allennlp.data.iterators.adaptive_iterator.AdaptiveIterator:13: ERROR: Undefined substitution referenced: "sentence2".
/Users/michael/hack/allenai/allennlp/allennlp/modules/augmented_lstm.py:docstring of allennlp.modules.augmented_lstm.AugmentedLstm:33: ERROR: Unexpected indentation.
/Users/michael/hack/allenai/allennlp/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py:docstring of allennlp.modules.seq2seq_encoders.pytorch_seq2seq_wrapper.PytorchSeq2SeqWrapper:11: ERROR: Unexpected indentation.
/Users/michael/hack/allenai/allennlp/allennlp/modules/similarity_functions/linear.py:docstring of allennlp.modules.similarity_functions.linear.LinearSimilarity:31: WARNING: Inline literal start-string without end-string.
/Users/michael/hack/allenai/allennlp/allennlp/nn/initializers.py:docstring of allennlp.nn.initializers.InitializerApplicator:17: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/michael/hack/allenai/allennlp/allennlp/nn/initializers.py:docstring of allennlp.nn.initializers.InitializerApplicator.from_params:0: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/michael/hack/allenai/allennlp/allennlp/training/regularizers/regularizer_applicator.py:docstring of allennlp.training.regularizers.regularizer_applicator.RegularizerApplicator:15: WARNING: Definition list ends without a blank line; unexpected unindent.
/Users/michael/hack/allenai/allennlp/allennlp/training/regularizers/regularizer_applicator.py:docstring of allennlp.training.regularizers.regularizer_applicator.RegularizerApplicator.from_params:0: WARNING: Definition list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                                                                                                      
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 18 warnings.

Build finished. The HTML pages are in build/html.
```

**Comment by schmmd** [comment]
Once this is merged, I can add documentation for `/doc` and figure out how to upload docs to ReadTheDocs.

**Comment by matt-gardner** [comment]
And this is where circle CI would be really helpful, to make sure that the docs build, and to be able to see the generated docs when looking at a PR.  We should be able to just copy configuration over from deepqa, and enable it on circle ci.  @schmmd, do you want to do that, or should I?

**Comment by schmmd** [comment]
@matt-gardner you should do it as you are familiar with it.  Should I fix the conflicts and merge this PR as a step forward for the time being?

**Comment by matt-gardner** [comment]
I don't think this should be merged without CI, and without docs that actually build without warnings.  I can set up CI and fix the remaining issues.

**Comment by schmmd** [comment]
Ah, I had missed the following:

```
) find . -name '*.rst'
./data/about_data.rst
./data/data_generator.rst
./data/datasets.rst
./data/entailment.rst
./data/general_data_utils.rst
./data/instances.rst
./data/reading_comprehension.rst
./data/sequence_tagging.rst
./data/text_classification.rst
./data/tokenizers.rst
./models/about_models.rst
./models/entailment.rst
./models/reading_comprehension.rst
./models/text_classification.rst
```

**Comment by matt-gardner** [comment]
@schmmd, finally got this to actually build.  Want to take a look?

**Comment by schmmd** [comment]
Looks good--although it's quite a big PR ;-)

**Comment by schmmd** [comment]
I'm not able to approve as I made the PR.

**Pull request merged**
