### PR TITLE
Use full version in docs.

### PR DESCRIPTION
**Pull request by schmmd**
False alarm on the docs not being deployed for previous releases.  I was confused by the version number reported in the UI.  This change will cause the docs to show the full version number.

### CODE REVIEW

**Comment by joelgrus** [comment]
I don't understand this change. There's a long version ("release") and a short version ("version"), and you're changing it so that they're both equal to the long version?

Isn't the "right" fix to change the sphinx config to use the other one?

**Comment by joelgrus** [comment]
oops, never mind, I misunderstood

**Comment by schmmd** [comment]
@joelgrus I wasn't sure if the comments before were even accurate.  This addresses the problem I wanted to fix--but there might be another way.  I couldn't figure another way too quickly however--and I really don't ever want Sphynx to show the short version number.  In fact--I think the only reason we have `VERSION_SHORT` is for Sphynx--should I just remove it entirely?

**Comment by joelgrus** [comment]
nah, I can imagine someone wanting to use it in theory, I think this way is fine

**Pull request merged**
