### PR TITLE
Streamlining the docker build a little bit

### PR DESCRIPTION
**Pull request by matt-gardner**
1. Minor tweaks to the order of copies in the dockerfile.
2. Redirecting stderr as well as stdout in the `EVALB` command.
3. Hiding building the demo behind an argument and a script, because it is slow.

It's possible that our tests rely on the demo; CI will tell us that for sure.  If so, I'll try to find a way to make the tests not rely on the demo...

@schmmd, this means that something has to change in the demo build, in the same place where `CACHE_MODELS=true` is specified, wherever that is.

### CODE REVIEW

**Comment by schmmd** [comment]
@matt-gardner what is your goal here?  To speed up continuous integration?  If that is your goal, I'm worried we'll need a much larger change than you have here since this will break our demo deployment system, which relies on our Docker images having the demo built.

**Comment by matt-gardner** [comment]
My goal is to reduce the time I sit waiting when I run `run_with_beaker.py`.

**Comment by matt-gardner** [comment]
I thought the demo build on teamcity passed in the `CACHE_MODELS=true` flag.  If so, it'd be trivial to also add in a `BUILD_DEMO=true` flag in the same place.  If that happens for all of CI, that's fine, as it's not as big a deal to wait a few more seconds on CI as it is to wait a few seconds on the command line when I'm starting an experiment.

**Comment by matt-gardner** [comment]
I just updated both of those places to include `--build-arg BUILD_DEMO=true`.  I'll verify that this did what I expected in this latest merge build.

**Comment by schmmd** [comment]
Ha, funny, at the exact same time you added me as a reviewer ;-)

**Comment by matt-gardner** [comment]
What's the difference between requesting a review and assigning a PR?

**Pull request merged**
