### PR TITLE
Update torchvision requirement from <0.9.0,>=0.8.1 to >=0.8.1,<0.10.0

### PR DESCRIPTION
**Pull request by nelson-liu**
Updates the requirements on [torchvision](https://github.com/pytorch/vision) to permit the latest version.

This is blocked by allenai/allennlp-models#225 , go look at that first.

### CODE REVIEW

**Comment by nelson-liu** [comment]
The models tests seem to be failing because GHA is checking out allennlp-models and then installing it, and `allennlp-models` prefers torch 1.7.1 for some reason, despite `ALLENNLP_VERSION_OVERRIDE: ""`. Indeed, it seems like allennlp is being re-downloaded and then overwritten by `allennlp-models`. any hints?

**Comment by nelson-liu** [comment]
Ah, torch is set in the `allennlp-models` `requirements.txt` as well (is this intended?) I'll uptick that too.

**Comment by nelson-liu** [comment]
Should just be able to add a changelog entry to https://github.com/allenai/allennlp-models/pull/225 and should be good to go. The core test failure is a bit mysterious to me, though, not immediately clear why it'd pop up with a newer version of torchvision in particular.

**Comment by nelson-liu** [comment]
Looks like #5037 didn't actually touch torch 1.8 because the torchvision dependency was keeping things behind :( I've fixed one of the core tests, but have yet to crack the failure on `TestCnnEncoder.test_forward_respects_masking`

**Comment by dirkgr** [comment]
I just merged #225. Will re-run the tests here now.

**Comment by dirkgr** [comment]
None of these fail locally :-(

**Comment by dirkgr** [comment]
This is not a very satisfying fix, but I am OK with it.

**Review by dirkgr — APPROVED** [review]

**Comment by nelson-liu** [comment]
fwiw: i was able to reproduce the CNNEncoder masking test failure locally. diffing the output tensors of the masked and unmasked encoder from pytorch 1.7.1 and 1.8.0, there was indeed a minute difference.

Not really sure what the cause could be, though. Spent some time looking into it but did not come up with anything.

**Pull request merged**
