### PR TITLE
Move jupyter dependency to requirements_test.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
@DeNeutoy I think Jupyter is only used to test our notebooks.  Do you know of any other uses for this dependency?

**Comment by DeNeutoy** [comment]
It's used to actually run the tutorial notebooks if you have cloned the repo and want to interactively work through the tutorials, so I think it's probably best to leave it here?

eg you can do:

```
jupyter notebook
```
in the root of the repo and then navigate to `tutorials/notebooks/some_tutorial` and actually run the python code interactively which is there.

**Comment by schmmd** [comment]
I see those notebooks as separate from our codebase and I think of Jupyter as a separate application to run those notebooks.  Jupyter also has far more subdependencies (see below) than any other dependency as it's essentially an entire web application.

We also install Jupyter in our setup.py--which definitely feels wrong to me since we don't distribute the notebooks with the pip installation.

That said, I'm not an expert on distributing Python applications.  I just put this PR together after a brief comment with @joelgrus, thinking it was a mistake.

```
jupyter==1.0.0
  - ipykernel [required: Any, installed: 4.7.0]
    - ipython [required: >=4.0.0, installed: 6.2.1]
      - appnope [required: Any, installed: 0.1.0]
      - decorator [required: Any, installed: 4.1.2]
      - jedi [required: >=0.10, installed: 0.11.0]
        - parso [required: ==0.1.0, installed: 0.1.0]
      - pexpect [required: Any, installed: 4.3.1]
        - ptyprocess [required: >=0.5, installed: 0.5.2]
      - pickleshare [required: Any, installed: 0.7.4]
      - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
        - six [required: >=1.9.0, installed: 1.11.0]
        - wcwidth [required: Any, installed: 0.1.7]
      - pygments [required: Any, installed: 2.2.0]
      - setuptools [required: >=18.5, installed: 36.4.0]
      - simplegeneric [required: >0.8, installed: 0.8.1]
      - traitlets [required: >=4.2, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - jupyter-client [required: Any, installed: 5.1.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - python-dateutil [required: >=2.1, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.11.0]
      - pyzmq [required: >=13, installed: 16.0.3]
      - traitlets [required: Any, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - tornado [required: >=4.0, installed: 4.5.2]
    - traitlets [required: >=4.1.0, installed: 4.3.2]
      - decorator [required: Any, installed: 4.1.2]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - six [required: Any, installed: 1.11.0]
  - ipywidgets [required: Any, installed: 7.0.5]
    - ipykernel [required: >=4.5.1, installed: 4.7.0]
      - ipython [required: >=4.0.0, installed: 6.2.1]
        - appnope [required: Any, installed: 0.1.0]
        - decorator [required: Any, installed: 4.1.2]
        - jedi [required: >=0.10, installed: 0.11.0]
          - parso [required: ==0.1.0, installed: 0.1.0]
        - pexpect [required: Any, installed: 4.3.1]
          - ptyprocess [required: >=0.5, installed: 0.5.2]
        - pickleshare [required: Any, installed: 0.7.4]
        - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
          - six [required: >=1.9.0, installed: 1.11.0]
          - wcwidth [required: Any, installed: 0.1.7]
        - pygments [required: Any, installed: 2.2.0]
        - setuptools [required: >=18.5, installed: 36.4.0]
        - simplegeneric [required: >0.8, installed: 0.8.1]
        - traitlets [required: >=4.2, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - jupyter-client [required: Any, installed: 5.1.0]
        - jupyter-core [required: Any, installed: 4.4.0]
          - traitlets [required: Any, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - python-dateutil [required: >=2.1, installed: 2.6.1]
          - six [required: >=1.5, installed: 1.11.0]
        - pyzmq [required: >=13, installed: 16.0.3]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - tornado [required: >=4.0, installed: 4.5.2]
      - traitlets [required: >=4.1.0, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - ipython [required: >=4.0.0, installed: 6.2.1]
      - appnope [required: Any, installed: 0.1.0]
      - decorator [required: Any, installed: 4.1.2]
      - jedi [required: >=0.10, installed: 0.11.0]
        - parso [required: ==0.1.0, installed: 0.1.0]
      - pexpect [required: Any, installed: 4.3.1]
        - ptyprocess [required: >=0.5, installed: 0.5.2]
      - pickleshare [required: Any, installed: 0.7.4]
      - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
        - six [required: >=1.9.0, installed: 1.11.0]
        - wcwidth [required: Any, installed: 0.1.7]
      - pygments [required: Any, installed: 2.2.0]
      - setuptools [required: >=18.5, installed: 36.4.0]
      - simplegeneric [required: >0.8, installed: 0.8.1]
      - traitlets [required: >=4.2, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - nbformat [required: >=4.2.0, installed: 4.4.0]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - jsonschema [required: >=2.4,!=2.5.0, installed: 2.6.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - traitlets [required: >=4.1, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - traitlets [required: >=4.3.1, installed: 4.3.2]
      - decorator [required: Any, installed: 4.1.2]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - six [required: Any, installed: 1.11.0]
    - widgetsnbextension [required: ~=3.0.0, installed: 3.0.8]
      - notebook [required: >=4.4.1, installed: 5.2.2]
        - ipykernel [required: Any, installed: 4.7.0]
          - ipython [required: >=4.0.0, installed: 6.2.1]
            - appnope [required: Any, installed: 0.1.0]
            - decorator [required: Any, installed: 4.1.2]
            - jedi [required: >=0.10, installed: 0.11.0]
              - parso [required: ==0.1.0, installed: 0.1.0]
            - pexpect [required: Any, installed: 4.3.1]
              - ptyprocess [required: >=0.5, installed: 0.5.2]
            - pickleshare [required: Any, installed: 0.7.4]
            - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
              - six [required: >=1.9.0, installed: 1.11.0]
              - wcwidth [required: Any, installed: 0.1.7]
            - pygments [required: Any, installed: 2.2.0]
            - setuptools [required: >=18.5, installed: 36.4.0]
            - simplegeneric [required: >0.8, installed: 0.8.1]
            - traitlets [required: >=4.2, installed: 4.3.2]
              - decorator [required: Any, installed: 4.1.2]
              - ipython-genutils [required: Any, installed: 0.2.0]
              - six [required: Any, installed: 1.11.0]
          - jupyter-client [required: Any, installed: 5.1.0]
            - jupyter-core [required: Any, installed: 4.4.0]
              - traitlets [required: Any, installed: 4.3.2]
                - decorator [required: Any, installed: 4.1.2]
                - ipython-genutils [required: Any, installed: 0.2.0]
                - six [required: Any, installed: 1.11.0]
            - python-dateutil [required: >=2.1, installed: 2.6.1]
              - six [required: >=1.5, installed: 1.11.0]
            - pyzmq [required: >=13, installed: 16.0.3]
            - traitlets [required: Any, installed: 4.3.2]
              - decorator [required: Any, installed: 4.1.2]
              - ipython-genutils [required: Any, installed: 0.2.0]
              - six [required: Any, installed: 1.11.0]
          - tornado [required: >=4.0, installed: 4.5.2]
          - traitlets [required: >=4.1.0, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - jinja2 [required: Any, installed: 2.10]
          - MarkupSafe [required: >=0.23, installed: 1.0]
        - jupyter-client [required: Any, installed: 5.1.0]
          - jupyter-core [required: Any, installed: 4.4.0]
            - traitlets [required: Any, installed: 4.3.2]
              - decorator [required: Any, installed: 4.1.2]
              - ipython-genutils [required: Any, installed: 0.2.0]
              - six [required: Any, installed: 1.11.0]
          - python-dateutil [required: >=2.1, installed: 2.6.1]
            - six [required: >=1.5, installed: 1.11.0]
          - pyzmq [required: >=13, installed: 16.0.3]
          - traitlets [required: Any, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - jupyter-core [required: Any, installed: 4.4.0]
          - traitlets [required: Any, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - nbconvert [required: Any, installed: 5.3.1]
          - bleach [required: Any, installed: 2.1.2]
            - html5lib [required: !=1.0b2,!=1.0b1,>=0.99999999pre,!=1.0b5,!=1.0b3,!=1.0b8,!=1.0b6,!=1.0b4,!=1.0b7, installed: 1.0.1]
              - six [required: >=1.9, installed: 1.11.0]
              - webencodings [required: Any, installed: 0.5.1]
            - six [required: Any, installed: 1.11.0]
          - entrypoints [required: >=0.2.2, installed: 0.2.3]
          - jinja2 [required: Any, installed: 2.10]
            - MarkupSafe [required: >=0.23, installed: 1.0]
          - jupyter-core [required: Any, installed: 4.4.0]
            - traitlets [required: Any, installed: 4.3.2]
              - decorator [required: Any, installed: 4.1.2]
              - ipython-genutils [required: Any, installed: 0.2.0]
              - six [required: Any, installed: 1.11.0]
          - mistune [required: >=0.7.4, installed: 0.8.3]
          - nbformat [required: >=4.4, installed: 4.4.0]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - jsonschema [required: >=2.4,!=2.5.0, installed: 2.6.0]
            - jupyter-core [required: Any, installed: 4.4.0]
              - traitlets [required: Any, installed: 4.3.2]
                - decorator [required: Any, installed: 4.1.2]
                - ipython-genutils [required: Any, installed: 0.2.0]
                - six [required: Any, installed: 1.11.0]
            - traitlets [required: >=4.1, installed: 4.3.2]
              - decorator [required: Any, installed: 4.1.2]
              - ipython-genutils [required: Any, installed: 0.2.0]
              - six [required: Any, installed: 1.11.0]
          - pandocfilters [required: >=1.4.1, installed: 1.4.2]
          - pygments [required: Any, installed: 2.2.0]
          - testpath [required: Any, installed: 0.3.1]
          - traitlets [required: >=4.2, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - nbformat [required: Any, installed: 4.4.0]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - jsonschema [required: >=2.4,!=2.5.0, installed: 2.6.0]
          - jupyter-core [required: Any, installed: 4.4.0]
            - traitlets [required: Any, installed: 4.3.2]
              - decorator [required: Any, installed: 4.1.2]
              - ipython-genutils [required: Any, installed: 0.2.0]
              - six [required: Any, installed: 1.11.0]
          - traitlets [required: >=4.1, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - terminado [required: >=0.3.3, installed: 0.8.1]
          - ptyprocess [required: Any, installed: 0.5.2]
          - tornado [required: >=4, installed: 4.5.2]
        - tornado [required: >=4, installed: 4.5.2]
        - traitlets [required: >=4.2.1, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
  - jupyter-console [required: Any, installed: 5.2.0]
    - ipykernel [required: Any, installed: 4.7.0]
      - ipython [required: >=4.0.0, installed: 6.2.1]
        - appnope [required: Any, installed: 0.1.0]
        - decorator [required: Any, installed: 4.1.2]
        - jedi [required: >=0.10, installed: 0.11.0]
          - parso [required: ==0.1.0, installed: 0.1.0]
        - pexpect [required: Any, installed: 4.3.1]
          - ptyprocess [required: >=0.5, installed: 0.5.2]
        - pickleshare [required: Any, installed: 0.7.4]
        - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
          - six [required: >=1.9.0, installed: 1.11.0]
          - wcwidth [required: Any, installed: 0.1.7]
        - pygments [required: Any, installed: 2.2.0]
        - setuptools [required: >=18.5, installed: 36.4.0]
        - simplegeneric [required: >0.8, installed: 0.8.1]
        - traitlets [required: >=4.2, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - jupyter-client [required: Any, installed: 5.1.0]
        - jupyter-core [required: Any, installed: 4.4.0]
          - traitlets [required: Any, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - python-dateutil [required: >=2.1, installed: 2.6.1]
          - six [required: >=1.5, installed: 1.11.0]
        - pyzmq [required: >=13, installed: 16.0.3]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - tornado [required: >=4.0, installed: 4.5.2]
      - traitlets [required: >=4.1.0, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - ipython [required: Any, installed: 6.2.1]
      - appnope [required: Any, installed: 0.1.0]
      - decorator [required: Any, installed: 4.1.2]
      - jedi [required: >=0.10, installed: 0.11.0]
        - parso [required: ==0.1.0, installed: 0.1.0]
      - pexpect [required: Any, installed: 4.3.1]
        - ptyprocess [required: >=0.5, installed: 0.5.2]
      - pickleshare [required: Any, installed: 0.7.4]
      - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
        - six [required: >=1.9.0, installed: 1.11.0]
        - wcwidth [required: Any, installed: 0.1.7]
      - pygments [required: Any, installed: 2.2.0]
      - setuptools [required: >=18.5, installed: 36.4.0]
      - simplegeneric [required: >0.8, installed: 0.8.1]
      - traitlets [required: >=4.2, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - jupyter-client [required: Any, installed: 5.1.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - python-dateutil [required: >=2.1, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.11.0]
      - pyzmq [required: >=13, installed: 16.0.3]
      - traitlets [required: Any, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - prompt-toolkit [required: <2.0.0,>=1.0.0, installed: 1.0.15]
      - six [required: >=1.9.0, installed: 1.11.0]
      - wcwidth [required: Any, installed: 0.1.7]
    - pygments [required: Any, installed: 2.2.0]
  - nbconvert [required: Any, installed: 5.3.1]
    - bleach [required: Any, installed: 2.1.2]
      - html5lib [required: !=1.0b2,!=1.0b1,>=0.99999999pre,!=1.0b5,!=1.0b3,!=1.0b8,!=1.0b6,!=1.0b4,!=1.0b7, installed: 1.0.1]
        - six [required: >=1.9, installed: 1.11.0]
        - webencodings [required: Any, installed: 0.5.1]
      - six [required: Any, installed: 1.11.0]
    - entrypoints [required: >=0.2.2, installed: 0.2.3]
    - jinja2 [required: Any, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - jupyter-core [required: Any, installed: 4.4.0]
      - traitlets [required: Any, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - mistune [required: >=0.7.4, installed: 0.8.3]
    - nbformat [required: >=4.4, installed: 4.4.0]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - jsonschema [required: >=2.4,!=2.5.0, installed: 2.6.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - traitlets [required: >=4.1, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - pandocfilters [required: >=1.4.1, installed: 1.4.2]
    - pygments [required: Any, installed: 2.2.0]
    - testpath [required: Any, installed: 0.3.1]
    - traitlets [required: >=4.2, installed: 4.3.2]
      - decorator [required: Any, installed: 4.1.2]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - six [required: Any, installed: 1.11.0]
  - notebook [required: Any, installed: 5.2.2]
    - ipykernel [required: Any, installed: 4.7.0]
      - ipython [required: >=4.0.0, installed: 6.2.1]
        - appnope [required: Any, installed: 0.1.0]
        - decorator [required: Any, installed: 4.1.2]
        - jedi [required: >=0.10, installed: 0.11.0]
          - parso [required: ==0.1.0, installed: 0.1.0]
        - pexpect [required: Any, installed: 4.3.1]
          - ptyprocess [required: >=0.5, installed: 0.5.2]
        - pickleshare [required: Any, installed: 0.7.4]
        - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
          - six [required: >=1.9.0, installed: 1.11.0]
          - wcwidth [required: Any, installed: 0.1.7]
        - pygments [required: Any, installed: 2.2.0]
        - setuptools [required: >=18.5, installed: 36.4.0]
        - simplegeneric [required: >0.8, installed: 0.8.1]
        - traitlets [required: >=4.2, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - jupyter-client [required: Any, installed: 5.1.0]
        - jupyter-core [required: Any, installed: 4.4.0]
          - traitlets [required: Any, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - python-dateutil [required: >=2.1, installed: 2.6.1]
          - six [required: >=1.5, installed: 1.11.0]
        - pyzmq [required: >=13, installed: 16.0.3]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - tornado [required: >=4.0, installed: 4.5.2]
      - traitlets [required: >=4.1.0, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - ipython-genutils [required: Any, installed: 0.2.0]
    - jinja2 [required: Any, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
    - jupyter-client [required: Any, installed: 5.1.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - python-dateutil [required: >=2.1, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.11.0]
      - pyzmq [required: >=13, installed: 16.0.3]
      - traitlets [required: Any, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - jupyter-core [required: Any, installed: 4.4.0]
      - traitlets [required: Any, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - nbconvert [required: Any, installed: 5.3.1]
      - bleach [required: Any, installed: 2.1.2]
        - html5lib [required: !=1.0b2,!=1.0b1,>=0.99999999pre,!=1.0b5,!=1.0b3,!=1.0b8,!=1.0b6,!=1.0b4,!=1.0b7, installed: 1.0.1]
          - six [required: >=1.9, installed: 1.11.0]
          - webencodings [required: Any, installed: 0.5.1]
        - six [required: Any, installed: 1.11.0]
      - entrypoints [required: >=0.2.2, installed: 0.2.3]
      - jinja2 [required: Any, installed: 2.10]
        - MarkupSafe [required: >=0.23, installed: 1.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - mistune [required: >=0.7.4, installed: 0.8.3]
      - nbformat [required: >=4.4, installed: 4.4.0]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - jsonschema [required: >=2.4,!=2.5.0, installed: 2.6.0]
        - jupyter-core [required: Any, installed: 4.4.0]
          - traitlets [required: Any, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - traitlets [required: >=4.1, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - pandocfilters [required: >=1.4.1, installed: 1.4.2]
      - pygments [required: Any, installed: 2.2.0]
      - testpath [required: Any, installed: 0.3.1]
      - traitlets [required: >=4.2, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - nbformat [required: Any, installed: 4.4.0]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - jsonschema [required: >=2.4,!=2.5.0, installed: 2.6.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - traitlets [required: >=4.1, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - terminado [required: >=0.3.3, installed: 0.8.1]
      - ptyprocess [required: Any, installed: 0.5.2]
      - tornado [required: >=4, installed: 4.5.2]
    - tornado [required: >=4, installed: 4.5.2]
    - traitlets [required: >=4.2.1, installed: 4.3.2]
      - decorator [required: Any, installed: 4.1.2]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - six [required: Any, installed: 1.11.0]
  - qtconsole [required: Any, installed: 4.3.1]
    - ipykernel [required: >=4.1, installed: 4.7.0]
      - ipython [required: >=4.0.0, installed: 6.2.1]
        - appnope [required: Any, installed: 0.1.0]
        - decorator [required: Any, installed: 4.1.2]
        - jedi [required: >=0.10, installed: 0.11.0]
          - parso [required: ==0.1.0, installed: 0.1.0]
        - pexpect [required: Any, installed: 4.3.1]
          - ptyprocess [required: >=0.5, installed: 0.5.2]
        - pickleshare [required: Any, installed: 0.7.4]
        - prompt-toolkit [required: <2.0.0,>=1.0.4, installed: 1.0.15]
          - six [required: >=1.9.0, installed: 1.11.0]
          - wcwidth [required: Any, installed: 0.1.7]
        - pygments [required: Any, installed: 2.2.0]
        - setuptools [required: >=18.5, installed: 36.4.0]
        - simplegeneric [required: >0.8, installed: 0.8.1]
        - traitlets [required: >=4.2, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - jupyter-client [required: Any, installed: 5.1.0]
        - jupyter-core [required: Any, installed: 4.4.0]
          - traitlets [required: Any, installed: 4.3.2]
            - decorator [required: Any, installed: 4.1.2]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.11.0]
        - python-dateutil [required: >=2.1, installed: 2.6.1]
          - six [required: >=1.5, installed: 1.11.0]
        - pyzmq [required: >=13, installed: 16.0.3]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - tornado [required: >=4.0, installed: 4.5.2]
      - traitlets [required: >=4.1.0, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - ipython-genutils [required: Any, installed: 0.2.0]
    - jupyter-client [required: >=4.1, installed: 5.1.0]
      - jupyter-core [required: Any, installed: 4.4.0]
        - traitlets [required: Any, installed: 4.3.2]
          - decorator [required: Any, installed: 4.1.2]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.11.0]
      - python-dateutil [required: >=2.1, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.11.0]
      - pyzmq [required: >=13, installed: 16.0.3]
      - traitlets [required: Any, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - jupyter-core [required: Any, installed: 4.4.0]
      - traitlets [required: Any, installed: 4.3.2]
        - decorator [required: Any, installed: 4.1.2]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.11.0]
    - pygments [required: Any, installed: 2.2.0]
    - traitlets [required: Any, installed: 4.3.2]
      - decorator [required: Any, installed: 4.1.2]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - six [required: Any, installed: 1.11.0]
```

**Comment by joelgrus** [comment]
if it were me, I probably wouldn't include `jupyter` as a library requirement, and would just tell people to install it in the notebook tutorial instructions.

but I don't feel super strongly about removing it.

**Comment by schmmd** [comment]
Up to you @DeNeutoy !  If you want to leave it in requirements.txt I'll remove it from setup.py.

If you're OK removing it from requirements.txt, I'll update the instructions on our tutorials.

With large dependency trees, I worry about nuanced dependency issues from incompatible transitive dependencies--particularly as we pin dependencies.

**Comment by DeNeutoy** [comment]
Sure, updating instructions in the notebooks and removing it sounds fine.

**Comment by schmmd** [comment]
Cool.  The following also convinced me this is a good idea:

```
$ pipdeptree -p jupyter | wc -l
506
$ pipdeptree | wc -l 
707
```

**Pull request merged**
