### PR TITLE
Add conda builds for allennlp

### PR DESCRIPTION
**Pull request by nelson-liu**
I've set up an experimental feedstock for automatically building AllenNLP packages here: https://github.com/nelson-liu/allennlp-feedstock . You can see that the package is built by public CI, run through the test suite, and then pushed up to conda. I'm currently hosting this on my own `nfliu` channel for testing purposes, but it'd be easy to move it over to an `allennlp` channel.

to install allennlp with conda, use:
```
conda install allennlp cuda90 -c pytorch -c nfliu -c conda-forge
```

(note that you need `cuda90` for now because `pytorch 0.3.1` on conda is broken due to some cudnn issues (https://github.com/pytorch/pytorch/issues/5667#issuecomment-381361397). Once we upgrade to 0.4, we can get rid of the 'cuda90' part).

I've also added a `CONDA_BUILD_HOWTO.md` to the root directory. I don't really mind where this goes, or if this PR is merged at all. I'm just using it as a means to have a discussion about this.

I have tested both of the packages in [the `nfliu` channel](https://anaconda.org/nfliu/allennlp/files), and I'm able to successfully run the v0.4.3 test suite on osx and linux with cuda.

Let me know your thoughts on this. To set this up under the allennlp namespace, i'd need you to:

~~1) Make an `allennlp-feedstock` repo under `allenai`~~ (requirement 4 subsumes this)

2) set up allenai organizational accounts for `travisci`, `circleci`, and `appveyor` (all free).

3) Generate tokens for circle and appveyor at:
  - https://circleci.com/account/api
  - https://ci.appveyor.com/api-token

4) Generate a Github token for the allenai organization with "repo" permissions at https://github.com/settings/tokens/new . `conda-smithy` with automatically create the repo in the `allenai` org and link CI.

Alternatively, you can set up the feedstock yourself with the instructions at https://github.com/conda-forge/conda-smithy#setup . you just need to use the `conda-forge.yml` in my repo and the recipe there as well.

thanks! feel free to ask any questions below. Of course, I'm happy to maintain this (and it's minimal work anyway).

### CODE REVIEW

**Comment by DeNeutoy** [comment]
🙏 🙏 🙏 🙏 

Question: How does this not install pytorch for cuda 8 by default? I'd imagine that would break things... I checked out the new `allennlp-conda-linux-anvil` repo but I couldn't see a point where you had a different Dockerfile for cuda90.

**Comment by nelson-liu** [comment]
Hmm, im a bit confused, since it does install pytorch for cuda8 by default? To be more clear:

conda install allennlp -c pytorch -c nfliu -c conda-forge gives you allennlp + cuda 8

conda install allennlp cuda90 -c pytorch -c nfliu -c conda-forge gives you allennlp + cuda 9

conda install allennlp cuda91-c pytorch -c nfliu -c conda-forge gives you allennlp + cuda9.1

Or did i misunderstand your question?

**Comment by DeNeutoy** [comment]
Another question - what is the purpose of the multiple CIs? Is that for conda to test our package?

**Comment by DeNeutoy** [comment]
I guess I was more asking - can we not use only one CI?

**Comment by nelson-liu** [comment]
i don't think so, not now at least. Conda generally has different packages for osx, linux, and windows, so we need at least an osx vm and a linux vm to build, test, and upload.

When we get windows support, we can turn the conda package into a [`noarch`](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#architecture-independent-packages) package, which indicates that the codebase is platform invariant. When we do that, `conda-smithy` will automatically switch to just using 1 CI (circle).

**Comment by matt-gardner** [comment]
To be clear, then, you're saying that it's conda that uses those other CIs, and we just need to generate tokens so conda can do its thing?

**Comment by nelson-liu** [comment]
fwiw, @dallascard mentioned to me today that he was googling for an allennlp conda package and found this... :)

**Comment by matt-gardner** [comment]
@nelson-liu, who's the right person to review / approve this?  You want to request a review or assign someone?  I don't think the right person is me - I haven't touched hardly any of our build process.

**Comment by nelson-liu** [comment]
I really don’t know either. There isn’t a bunch of code to review or anything; im happy to maintain for the foreseeable future, and the release process is pretty transparent because it all happens on a GitHub PR so anyone who wants to learn how to do it can quickly catch on. 

It’s just about whether it’s desirable to move the materials to the allenai organization / whether you want to have this in an allennlp conda channel.

**Comment by DeNeutoy** [comment]
The problem is, if it isn't built by the CI, it will definitely_ break. It's not feasible to maintain it long term unless it's automated, I think. It will also add a major complexity to the release process, which is already not straightforward. Do you have any thoughts on how to fix some of these concerns?

**Comment by nelson-liu** [comment]
> The problem is, if it isn't built by the CI, it will definitely break. It's not feasible to maintain it long term unless it's automated, I think.

It is almost completely automated, though. The only changes you need to make on most releases is to increment the version and the hash (see an example update for the pytest package at https://github.com/conda-forge/pytest-feedstock/pull/44, literally a 4 line diff that conda-forge has built a bot for).

> It will also add a major complexity to the release process, which is already not straightforward. 

Again, I think you're really overestimating how much effort it takes to make this work once it's set up. I'm happy to walk through it in detail, in-person when I start next week if you think that'd be helpful.

**Comment by nelson-liu** [comment]
speaking of which, the body of that PR has this neat tool https://regro.github.io/rever-docs/ that might be useful for automating some of the release process (e.g. automatically incrementing version numbers and such)?

**Comment by joelgrus** [comment]
this adds extra complexity for not much benefit, closing

**Pull request closed without merging**
