### PR TITLE
allow tests to run in parallel

### PR DESCRIPTION
**Pull request by joelgrus**
in order to do this I needed to make AllenNLPTestCase.TEST_DIR depend on os.getpid(), so that different processes have different TEST_DIRs, otherwise they clobber each other.

on my macbook:

```
$ time pytest -n 8

real	2m35.736s
user	5m14.864s
sys	0m28.034s
```

vs

```
$ time pytest

real	3m47.364s
user	3m47.823s
sys	0m19.338s
```

so that shaves more than a minute off the wall-clock time

### CODE REVIEW

**Comment by schmmd** [comment]
Nice!  Yeah--tests are getting a bit slow.

**Comment by schmmd** [comment]
I think this change will lead to non-deterministic failures since all our test files are written out to the same directory.  Before we merge this, I think we need to do something like https://github.com/allenai/allennlp/pull/1556.

**Comment by schmmd** [comment]
Oh, oops!  I see you did isolate tests by process!  That seems reasonable, although I like the solution in #1556 more.   Even better, I'd like to move to https://docs.pytest.org/en/latest/tmpdir.html but that's a lot of work for how our tests are laid out.

**Comment by joelgrus** [comment]
doesn't add much value

**Pull request closed without merging**
