### PR TITLE
WIP: Upgrade to Cuda 9.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
I'm going to run a test job using Beaker.

**Comment by schmmd** [comment]
I don't see any reason not to merge this PR now since:

* AllenNLP currently doesn't run on Beaker.
* It's easy to set up a GPU machine that can run GPU jobs with the Cuda 9 PyTorch install.
* We ultimately want to move to Cuda 9 to support V100s.

**Comment by schmmd** [comment]
@splittingfield FYI here's an error from running AllenNLP on PyTorch 0.3 with Cuda 8.

http://beaker.allenai.org/tk/tk_l2l7xl5od0m3

```
2017-12-20T18:36:22.029168368Z AssertionError: 
2017-12-20T18:36:22.029172066Z The NVIDIA driver on your system is too old (found version 8000).
2017-12-20T18:36:22.029176285Z Please update your GPU driver by downloading and installing a new
2017-12-20T18:36:22.029180202Z version from the URL: http://www.nvidia.com/Download/index.aspx
2017-12-20T18:36:22.02918528Z Alternatively, go to: http://pytorch.org to install
2017-12-20T18:36:22.029189907Z a PyTorch version that has been compiled with your version
2017-12-20T18:36:22.029193887Z of the CUDA driver.
```

**Comment by splittingfield** [comment]
Do you mean cuda 9?

**Comment by schmmd** [comment]
No--that error was with PyTorch and Cuda 8.  I'm running a new job with Cuda 9 and I expect to get the same error.  Presently it's not possible to run AllenNLP master (which uses PyTorch 0.3) with Beaker.

**Comment by splittingfield** [comment]
Sorry, I am a bit confused.  This change seems to pull a new version of cuda.  The previous version, before this change, did run with Beaker correct? We have many experiments using allennlp and the run with beaker shell script.

**Comment by DeNeutoy** [comment]
@schmmd http://beaker.allenai.org/tk/tk_qdtvig8vqu5q Ran fine, maybe you accidentally used the CUDA 9 binary?

**Comment by DeNeutoy** [comment]
Yeah that docker image is built with CUDA 9:

```
cat /usr/local/lib/python3.6/site-packages/torch/version.py
__version__ = '0.3.0.post4'
debug = False
cuda = '9.0.176'
```

**Comment by schmmd** [comment]
@DeNeutoy thanks for correcting me.  I must have gotten confused about my runs.

**Comment by splittingfield** [comment]
FYI, Google GPUS currently only support CUDA8 according to the updated docs I have.

**Pull request closed without merging**
