### PR TITLE
Update ELMo command help docstring

### PR DESCRIPTION
**Pull request by nelson-liu**
just ran `allennlp elmo --help` and updated the output.

### CODE REVIEW

**Comment by nelson-liu** [comment]
while i'm here: I'm interested in getting lowercased elmo vectors from `allennlp elmo`. is this part of `options_file`, or should I add a flag to the command?

**Comment by nelson-liu** [comment]
I’m interested in reproducing the functionality of the following snippet with lowercase_tokens set to True

```
 "dataset_reader": {
   "type": "srl",
   "token_indexers": {
     "tokens": {
       "type": "single_id",
       "lowercase_tokens": true
     },
     "elmo": {
       "type": "elmo_characters"
     }
   }
 }
```

**Comment by matt-peters** [comment]
It may be useful for lowercasing tokens with word vectors such as GloVe that were trained with lowercased tokens, but for ELMo it's not necessary which is why we haven't implemented it.

**Comment by schmmd** [comment]
Thanks!

**Pull request merged**
