### PR TITLE
Update install tutorial for PyTorch 0.3, mention python setup.py install

### PR DESCRIPTION
**Pull request by nelson-liu**
I was reading the installation tutorial to figure out how to build from source to contribute, and I noticed that there was no mention of actually running `python setup.py install` to install the cloned version of allennlp. This PR fixes that.

In addition, there are still some mentions of PyTorch 0.2 when it looks like you've moved on to 0.3 --- changed those as well.

### CODE REVIEW

**Comment by matt-gardner** [comment]
@joelgrus, @schmmd, one of you want to look at this?  You're more familiar with this than I am.

**Comment by nelson-liu** [comment]
Alternatively, maybe `pip install --editable .` is better for folks who want to contribute?

**Comment by schmmd** [comment]
@DeNeutoy I agree.  @nelson-liu let me push a commit to this PR.

**Comment by schmmd** [comment]
@nelson-liu I don't think the following is necessary:

```
Finally, install the package from source:

$ python setup.py install
```

You've already cloned the repository and installed the requirements.  The instructions intend for you to run from the `allennlp` directory.

**Comment by nelson-liu** [comment]
> The instructions intend for you to run from the allennlp directory.

Oh whoops, I assumed that the instructions were for using it as a module in some other code. Yes, then it makes sense to leave it as it is --- sorry!. If you're planning on pushing another commit, do you want to change this as well while you're at it?

**Comment by schmmd** [comment]
No worries, thanks @nelson-liu !

**Pull request merged**
