### PR TITLE
Skip a test that we know will fail

### PR DESCRIPTION
**Pull request by dirkgr**
This should fix, or at least go somewhat towards fixing, #3570.

### CODE REVIEW

**Comment by schmmd** [comment]
Makes sense to skip tests that are reliably failing.  @brendan-ai2 should we cut an issue to fix this test?

**Comment by brendan-ai2** [comment]
We'll be deleting this code soon. I wouldn't worry about making an issue for it.

**Comment by schmmd** [comment]
👍

**Comment by brendan-ai2** [comment]
Somewhat tangentially, we don't reliably support macOS since we don't have CI for it. This is embarrassing. At some point it would be great to look into getting a macOS machine in the cloud to run our tests.

**Comment by DeNeutoy** [comment]
@dirkgr - for PRs like this feel free to just squash and merge, we all need that extra spice in our lives

**Comment by schmmd** [comment]
👍 to @DeNeutoy 's comment.  We only brought the master merge back because--without it--GitHub doesn't give you the option to merge in master (which is useful sometimes).

**Pull request merged**
