### PR TITLE
Fix logging

### LINKED ISSUE #3785: Fix file friendly logging
@OyvindTafjord has identified a bug in our (formerly) file friendly logging that originated during the DistributedDataParallel additions. In short, `--file-friendly-logging` does not appear to work anymore.

To quote his Slack message:

> Regarding the lack of file-friendly logging: I'm guessing it's the distributed code (https://github.com/allenai/allennlp/pull/3529). As a workaround I hacked in the earlier code and that now works for my purposes (https://github.com/OyvindTafjord/allennlp/commit/8a1c7adaf78d3a1c2412312760b31192be936b0c). I also note that another change was that the stderr.log file for better or worse used to record these tqdm statuses, but with the new code that doesn't seem to happen (maybe that was intentional, but occasionally I have made use of those to get a post-hoc rough "training curve", although when using beaker those are also in the main beaker log).

### PR DESCRIPTION
**Pull request by epwalsh**
Closes #3785 and also ensures tqdm logged to file.

The solution just patches `sys.stdout` and `sys.stderr` with our own `TeeHandler` class.

@OyvindTafjord pinging you so you can give this a review as well

## Example output

**With `--file-friendly-logging`**

image

**Without `--file-friendly-logging`**

image

And in both cases the `stderr.log` looks like this:

image

## Downsides

- Relies on patching `sys.stdout` and `sys.stderr`. This is scary.
- The tqdm progress bars are not as pretty. Compare the output above to the status bars before this PR:

image

We can partially fix this by setting `ascii=False` when initializing the Tqdm instance. With that, it looks like this:

image

But it's still not as pretty because it doesn't take up the entire terminal width.

### CODE REVIEW

**Comment by matt-gardner** [comment]
We used to have a tee logger; did that get removed at some point?  Was that the cause of #3785?

**Comment by epwalsh** [comment]
I’m not sure when it was removed or why, but  I mostly copied it.

**Comment by OyvindTafjord** [comment]
Thanks! Looks good to me, although I don't have an opinion on the scariness of the fix. I don't particularly care about the formatting of the progress bars in normal mode, although having it span the terminal width doesn't seem all that important (or even preferable?).

Looks like the tee logger was removed in the PR https://github.com/allenai/allennlp/pull/3529 quoted in the issue https://github.com/allenai/allennlp/issues/3785.

**Comment by matt-gardner** [comment]
Oh, right.  @epwalsh, can you verify that this still works when using multiple GPUs?

**Comment by epwalsh** [comment]
I don’t have an environment set up yet with multiple GPUs, but I’ll have time tomorrow to spin one up. Until then, if anyone else is able to test on multiple GPUs LMK

**Comment by epwalsh** [comment]
Ok I gave it try on 2 GPUs on it looks like everything worked as expected. Here are some screen shots.

**Without `--file-friendly-logging` flag**

*Serialization directory*

image

*Terminal output during training*

image

*Worker 0 stderr log file*

image

*Worker 1 stderr log file*

image

*Worker 0 stdout log file*

image

*Worker 1 stdout log file*

image

**With `--file-friendly-logging` flag**

image

The log files looked the same as they did without the flag.

**Pull request merged**
