### PR TITLE
WIP: Use a temp directory for tests.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
Starting with one of the ELMo tests I start getting the error `OSError: [Errno 24] Too many open files: '/var/folders/v5/tlk1sh3d0l94fcmz10vtzmyh0000gn/T/tmpvnetszsn'` when running `shutil.rmtree`.  I didn't realize this at first because `tearDown` eats errors.

**Comment by nelson-liu** [comment]
maybe it might be easier to replace `/tmp/allennlp_tests` with `Path(tempfile.gettempdir()) / (allennlp_tests + current_username + a random hash to boot)` (using a random hash that makes the path unique if it isn't already)? 

Seems like it should achieve the same effect.

**Comment by schmmd** [comment]
@nelson-liu my backup plan (which I'm about to move to) is to replace `/tmp/allennlp_tests` with `tempfile.mkdtemp`--but to continue re-using the same directory for all our tests.

I'm worried regardless that we have a file leak in AllenNLP.

**Comment by schmmd** [comment]
Nope--looks like the root cause needs to be fixed in either case.  I have the same issue with the following change:

```
 import os
 import pathlib
 import shutil
+import tempfile
 from unittest import TestCase
 
 from allennlp.common.checks import log_pytorch_version_info
 
+TEST_DIR = pathlib.Path(tempfile.mkdtemp(prefix="allennlp_tests_"))
 
 class AllenNlpTestCase(TestCase):  # pylint: disable=too-many-public-methods
     """
@@ -31,8 +33,7 @@ class AllenNlpTestCase(TestCase):  # pylint: disable=too-many-public-methods
         logging.getLogger('urllib3.connectionpool').disabled = True
         log_pytorch_version_info()
 
-        self.TEST_DIR = pathlib.Path("/tmp/allennlp_tests/")
-
+        self.TEST_DIR = TEST_DIR
         os.makedirs(self.TEST_DIR, exist_ok=True)
 
     def tearDown(self):
```

**Comment by handsomezebra** [comment]
What's the current status of this issue? I am getting this error everytime on my mac environment, but not on my Linux environment.

`OSError: [Errno 24] Too many open files`

**Comment by nelson-liu** [comment]
@handsomezebra i think https://github.com/allenai/allennlp/pull/1564 was merged instead as a temporary fix for #1539 . @schmmd mentioned in that PR that he had to up his ulimit to get the tests to run --- perhaps that might work for you as well?

**Comment by handsomezebra** [comment]
Yes, using `ulimit -n 8192` solved most of the problem. Thanks!
But still all four s3 unit tests are failing for me on this machine. Did you guys see similar things? If not I can try some other machines and reproduce.

**Comment by nelson-liu** [comment]
Hmm, I cannot reproduce that. Can you open a new issue describing what you see, and we'll move the conversation there?

**Pull request closed without merging**
