### PR TITLE
Resolve some of the token_embedders warnings.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
I'm not done with this, but I wanted to ask about one approach I'm taking.  I removed `allennlp/tests/fixtures/bidaf/serialization/model.tar.gz` and instead use `allennlp/tests/fixtures/bidaf/serialization/` as the archive directory to load.  This means that `git` can track our changes and we don't need to include the vocabulary files twice (once inside the tarball and once outside).

Are there any concerns with this change @joelgrus @DeNeutoy @matt-gardner?  Otherwise I need to update the `model.tar.gz` itself.  If we go that route--would you un-tar and re-tar or rebuild the test fixture?

**Comment by DeNeutoy** [comment]
I would rather leave the tests using `model.tar.gz` because:

1. We distribute `model.tar.gz` files, not directories - it seems best to have our tests which check if models can train, save and load use the actual format we distribute.

2. The output in the `serialization` directories in the tests are generated using a command from the library (`train_model_from_file`) in this script: https://github.com/allenai/allennlp/blob/master/scripts/train_fixtures.py

Currently retraining the fixtures follows exactly the process of training a model. In order not to regenerate these `model.tar.gz` files, we would need to modify the behaviour of that script to remove the generated archive file.

3. Tracking the changes to the files inside the archives generated by test fixtures has relatively low value (as far as I can tell).

4. There are some differences between using a directory and using an archive in some edge cases #1052

**Comment by schmmd** [comment]
@DeNeutoy this is fine, but I wish you had spoken up earlier.  Fixing these warnings is rather painful and adding the `model.tar.gz` back will be a bit more pain ;-(.

We do test loading from a `tar.gz` in the sniff test.

**Comment by DeNeutoy** [comment]
Sorry, if you need immediate feedback you should post it in slack or message me directly or something.

**Comment by schmmd** [comment]
Yes, pretty uncontentious.  Unfortunately it leave a ton of warnings in the repo ;-P

**Comment by DeNeutoy** [comment]
Why does it leave warnings?

**Comment by schmmd** [comment]
@DeNeutoy the models need to be rebuilt with the new configuration.  When they are loaded presently they hit https://github.com/allenai/allennlp/blob/master/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L122.  I thought I'd try to work down our warnings a bit, but it's not terribly fun.  @joelgrus was wondering if we should just remove the warning from https://github.com/allenai/allennlp/blob/master/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L122--since it also hits us in the sniff tests, etc.

**Pull request merged**
