### PR TITLE
WIP: Add a Dockerfile for downstream dependencies.

### PR DESCRIPTION
**Pull request by schmmd**
Fixes https://github.com/allenai/allennlp/issues/1324.

### CODE REVIEW

**Comment by schmmd** [comment]
@joelgrus what do you think of this re-organization?

`ci/Dockerfile` would be used on:
* PRs
* Commits to master
  * On commits to master, it pushes images to `allennlp/build`.

`Dockerfile` would be only used on commits to master.
* On commits to master, it pushes images to `allennlp/commit`.

**Comment by joelgrus** [comment]
that seems fine to me, and there would be a CI step on `allennlp/commit` that runs `test-install`?

**Comment by schmmd** [comment]
@joelgrus yes--before pushing ;-)

**Comment by DeNeutoy** [comment]
The `/Dockerfile` won't actually be used to run the tests, is that right?

I'm not totally sure i've understood the idea here but I think if we are going to push an image with the updated pip installed package, don't we need to pip install the commit that was just merged? I don't think the downstream Dockerfile would currently support doing that.

**Comment by schmmd** [comment]
@DeNeutoy `/Dockerfile` won't be used for our continuous integration, but it will be use to run `test-install` for the pip distribution.  Once this is merged, the published image can be used as the base image in https://github.com/allenai/allennlp-demo/blob/master/Dockerfile.

You're right.  I need to modify `/Dockerfile` to correctly use git checkouts for pip installs.

**Comment by DeNeutoy** [comment]
Got it. Sounds good to me - a few clarifications:

1. How do we know when the pip install fails if it doesn't run on PRs? I guess this is just because it is slow (although it seems like they could run in parallel if we had more machines - is this not the case?).

2. This is still separate to the images we release for allennlp versions, right?

**Comment by schmmd** [comment]
@DeNeutoy 

Re 1--yes ideally it would run on PRs.  I don't want to do that as a first step because it's slow.

Re 2--yes it is separate from what we publish for releases.  However, soon I'd like to change what we publish as releases to be the pip Dockerfiles, rather than the CI Dockerfiles.  Do you see any concerns with my proposal here?

**Comment by DeNeutoy** [comment]
No, sounds good - I was just checking.

**Comment by schmmd** [comment]
LMK if you think of anything.  I'm a bit nervous changing our version Docker releases to be `pip` installations under the same namespace in case anyone is depending on them--but I'm pretty sure nobody is.

**Comment by schmmd** [comment]
@DeNeutoy I pushed a commit to allow source revision pip installations.

Unfortunately `test-install` doesn't pass.  (`FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'`).

**Comment by schmmd** [comment]
OK--after lunch I'm going to merge this (after approval @joelgrus) and set up CI to use `ci/Dockerfile` rather than `Dockerfile`.  Then I'll set up a task that build `Dockerfile` and runs test-install on Master Commit.  However--this is going to fail at first since some dependencies (such as Java) are missing.  I'm somewhat inclined to remove those tests (https://github.com/allenai/allennlp/blob/master/allennlp/commands/test_install.py#L61) from test-install--but we'll get there when we get there.

**Comment by matt-gardner** [comment]
I didn't look at this in detail at all (just deleting email that I don't need during some downtime); just piping in to say that `run_with_beaker.py` uses the dockerfile, so make sure that any reorganization doesn't break that script.  If you already made sure of that, great.

**Comment by schmmd** [comment]
@matt-gardner that's a good point (and one I overlooked).  It's a one-line change to fix.

**Comment by schmmd** [comment]
Alright--sorry for the added complexity the first go-round.

I've changed this PR to simply add a `Dockerfile.pip`, which ultimately causes far fewer changes but accomplishes the same goals.  On commits to master I will publish this Dockerfile to publish to `allennlp/pip/commit`.

**Pull request merged**
