### PR TITLE
Remove some Sphynx artifacts from the docs

### PR DESCRIPTION
**Pull request by schmmd**
* Remove occurrences of `.. codeblock:`
* Replace double backquotes with a single backquote.

### CODE REVIEW

**Comment by schmmd** [comment]
@DeNeutoy I'd like to test these changes locally but when I run `scripts/build_docs.py` locally I don't get any html files.  What do I need to do to build the docs as they are served?

**Comment by schmmd** [comment]
Ah... I just found `build_docs.sh`.

**Comment by schmmd** [comment]
@DeNeutoy changes look good locally.

**Comment by DeNeutoy** [comment]
@schmmd Feel free to remove that failing docstring test, it's too fragile - it's broken every single time we've changed the command line docstrings

**Comment by matt-gardner** [comment]
I disagree with removing that test - you're admitting that what shows up in the docs will be perpetually out of date.  If we want to remove the test, we should remove the docstrings that have the help text as well.

**Comment by schmmd** [comment]
@matt-gardner I removed them and cut https://github.com/allenai/allennlp/issues/3645 so I can take a look later.

**Comment by DeNeutoy** [comment]
Why not leave them in for now (so they appear in the docs) and make that issue something like "write a script which automatically replaces all the docstring comments in `commands`". I don't like that test because it's fiddly to fix, which means it should be a script which does it for you. We shouldn't check things we can automate instead.

**Comment by schmmd** [comment]
@DeNeutoy good call.  I'll update the issue.

**Comment by schmmd** [comment]
I'm ambivalent about whether we leave the doc strings in for the time being.

**Comment by schmmd** [comment]
I'm just going to revert the commands directory to avoid any debate ;-)

**Comment by DeNeutoy** [comment]
haha, this is what our tests should avoid - preventing us from making positive changes! But sounds good.

**Comment by schmmd** [comment]
Now I'm getting conflicts... I'll likely just merge this manually after resolving.

**Comment by DeNeutoy** [comment]
Sorry that was my fault - I tried to fix them but your fork is protected, so I can't push to it.

**Comment by DeNeutoy** [comment]
@schmmd FYI I deployed this, should be live shortly

**Pull request merged**
