### PR TITLE
Fix backslash exceptions.

### PR DESCRIPTION
**Pull request by schmmd**
I had trouble reproducing the same pytest output as @WrRan has on his PR locally, but here are a few more escape character fixes.

### CODE REVIEW

**Comment by schmmd** [comment]
@joelgrus assigning you since @DeNeutoy is out.

**Comment by joelgrus** [comment]
I asked mark about this issue a while back, he said he had no idea if this was an ok change?

**Comment by matt-gardner** [comment]
If it passes tests, I say go for it.  If it breaks something someone depends on, that person can add a better test that would have caught the problem.

**Comment by schmmd** [comment]
@joelgrus @matt-gardner I manually validated that each regular expression is unchanged with the `r'''` syntax--so I would be surprised if we have any problems.

**Comment by schmmd** [comment]
E.g.

```
In [1]: '~"\s*"i' == r'~"\s*"i'                                                                                                                                                                             
Out[1]: True
```

**Pull request merged**
