### PR TITLE
Make test_trainer_respects_keep_serialized_model_every_num_seconds more patient

### PR DESCRIPTION
**Pull request by nelson-liu**
Easy fix from #1206

### CODE REVIEW

**Comment by nelson-liu** [comment]
Hmm, @schmmd maybe you need to change the check that is required? I think you were editing TC recently

**Comment by schmmd** [comment]
@nelson-liu I think your PR might be in a weird state because I renamed "AllenNLP" to "AllenNLP Library" after this PR was created.  Rest assured--the check actually passed--it just never heard back from a check that started ("AllenNLP") because it was renamed.

**Comment by nelson-liu** [comment]
@schmmd ah ok, I tried to force push and rerun ci to see if that'd fix anything, but it doesn't look like it did. Maybe you can force the merge? Alternatively, you can let me know when the issue should be fixed and I'll push again to rerun ci

**Comment by allenai-dev-role** [comment]
Sorry @nelson-liu -- I didn't know you were unable to force the merge.  I would have been happy to earlier.

**Comment by matt-gardner** [comment]
@schmmd, it looks like there's still an issue here - the CI checks for #1364 are also in a weird state, and that one was just opened.

**Comment by schmmd** [comment]
@matt-gardner thanks for the pointer.

**Pull request merged**
