### PR TITLE
Revert "Add a test for the subcommands docstring help outputs"

### PR DESCRIPTION
**Pull request by DeNeutoy**
Reverts allenai/allennlp#3172

### CODE REVIEW

**Comment by DeNeutoy** [comment]
It's a bit brittle though, because if any library adds something that appears on import, these tests will break - and they change infrequently anyway. I didn't think about that at the time.

**Comment by bryant1410** [comment]
> It's a bit brittle though, because if any library adds something that appears on import, these tests will break - and they change infrequently anyway. I didn't think about that at the time.

They shouldn't print to the standard output. pytorch-transformers changed this behavior, and now logs messages (stderr).

**Comment by DeNeutoy** [comment]
Yeah, it doesn't matter that they shouldn't - they do, and many libraries will do this in the future.

**Comment by bryant1410** [comment]
> Yeah, it doesn't matter that they shouldn't - they do, and many libraries will do this in the future.

Okay. But I don't think it's a big deal. There's a solution also, which is to ignore some prefix in the output and maybe also a suffix (basically to search for a substring).

**Pull request closed without merging**
