### PR TITLE
Remove evaluation_json_file and _sanitize_json.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
@matt-gardner is this what you meant in https://github.com/allenai/allennlp/issues/244 by "but that parameter was removed a long time ago"?

**Comment by schmmd** [comment]
In addition to `pytest` I confirmed that BiDAF predictions and evaluations still work.

**Comment by matt-gardner** [comment]
Oh, I forgot that we just deprecated it.  Yes, this is what I meant.  As long as the models we're serving in our demo have been updated, then this is fine with me.  We don't want to break our demo with this, though.

**Comment by schmmd** [comment]
All of our models can make predictions with this change.

**Comment by matt-gardner** [comment]
Did you test the archived BiDAF model on S3?

**Comment by schmmd** [comment]
@matt-gardner yes--those are the models the demo uses.  I also tried them via `allennlp/run predict`. I did not try our past, inferior BiDAF models.

**Comment by schmmd** [comment]
I feel somewhat bad merging PR 404 on Friday the 13th.

**Pull request merged**
