### PR TITLE
Turn off shuffling during evaluation

### PR DESCRIPTION
**Pull request by nelson-liu**

### CODE REVIEW

**Comment by HarshTrivedi** [comment]
@nelson-liu  I keep getting this warning during validation evaluation after each epoch training. 
```
allennlp.data.iterators.bucket_iterator - shuffle parameter is set to False, while bucket iterators by definition change the order of your data.
```
Since shuffling for validation has been explicitly turned off, should warning for validation iterator be turned off ?

**Comment by nelson-liu** [comment]
I don't have a strong opinion either way, but you're right that the message isn't too useful now that validation shuffle is always false.

**Comment by matt-gardner** [comment]
I think it's probably fine to move that warning to a comment in the code.

**Comment by HarshTrivedi** [comment]
@matt-gardner That would cause the warning to not show for train iterator as well. Would that be fine?

**Comment by matt-gardner** [comment]
I think so.  The probability of running into the issue that's being warned about is _incredibly_ small, so we should optimize for the much more common case.

**Pull request merged**
