### PR TITLE
DOCS: Clean up the docs for commands

### PR DESCRIPTION
**Pull request by Bharat123rox**
Contributes to #3630 by :
- Cleaning up RST refs and replacing them with corresponding markdown refs
- Clean up backticks

I was unable to build the docs by running `/scripts/build_docs.sh` on my MacOS so please help me in verifying (generating a TeamCity build or some such process)

### CODE REVIEW

**Comment by epwalsh** [comment]
Hi @Bharat123rox, what issue were you having with building the docs? If you run “make serve-docs” that should work. If you get any errors let me know.

**Comment by Bharat123rox** [comment]
This is the error on running `make serve-docs` as well as `./scripts/build_docs.sh` :
```
Traceback (most recent call last):
  File "scripts/py2md.py", line 16, in <module>
    from nr.databind.core import Struct
ModuleNotFoundError: No module named 'nr'
make: *** [build-all-api-docs] Error 1
```

**Comment by epwalsh** [comment]
Did you run `pip install -r dev-requirements.txt`? If so, can you post the output of `pip freeze`?

**Comment by Bharat123rox** [comment]
After this it gives a new error (again same on `make serve-docs` or `./scripts/build_docs.sh`) :
```
Traceback (most recent call last):
  File "scripts/py2md.py", line 287, in <module>
    main()
  File "scripts/py2md.py", line 277, in main
    deque(p.imap(_py2md_wrapper, zip(opts.modules, outputs), chunk_size), maxlen=0)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 325, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
pydoc_markdown.interfaces.LoaderError: module "allennlp.training.metrics.spearman_correlation" not found
make: *** [build-all-api-docs] Error 1
```

**Comment by epwalsh** [comment]
Thanks @Bharat123rox, could you post the output of `pip freeze`?

**Comment by Bharat123rox** [comment]
> Thanks @Bharat123rox, could you post the output of `pip freeze`?

```
aiohttp==3.6.2
alabaster==0.7.12
allennlp==0.9.0
apex==0.1
appdirs==1.4.3
appnope==0.1.0
async-timeout==3.0.1
attrs==19.2.0
Babel==2.8.0
backcall==0.1.0
beautifulsoup4==4.8.1
black==19.3b0
bleach==3.1.0
blis==0.2.4
boto3==1.12.41
botocore==1.15.41
bs4==0.0.1
certifi==2019.9.11
cffi==1.13.2
cfgv==3.1.0
chardet==3.0.4
Click==7.0
codecov==2.0.22
conllu==1.3.1
coverage==5.1
cryptography==2.8
cycler==0.10.0
cymem==2.0.3
Cython==0.29.16
decorator==4.4.0
defusedxml==0.6.0
Deprecated==1.2.7
distlib==0.3.0
docutils==0.15.2
editdistance==0.5.3
entrypoints==0.3
filelock==3.0.12
flake8==3.7.9
flaky==3.6.1
Flask==1.1.2
Flask-Cors==3.0.8
ftfy==5.7
future==0.18.2
gevent==20.4.0
gitdb==4.0.4
github3.py==1.3.0
GitPython==3.1.1
greenlet==0.4.15
h5py==2.10.0
identify==1.4.15
idna==2.8
imagesize==1.2.0
importlib-metadata==0.23
ipykernel==5.1.3
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
itsdangerous==1.1.0
jedi==0.15.1
Jinja2==2.10.3
jmespath==0.9.5
joblib==0.14.1
jsonnet==0.15.0
jsonpickle==1.4.1
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.0
jwcrypto==0.6.0
keyring==21.2.0
kiwisolver==1.1.0
livereload==2.6.1
lunr==0.5.6
lxml==4.4.2
Markdown==3.2.1
markdown-include==0.5.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
mistune==0.8.4
mkdocs==1.1
mkdocs-material==5.1.0
mkdocs-material-extensions==1.0b2
more-itertools==7.2.0
multidict==4.7.5
murmurhash==1.0.2
mypy==0.770
mypy-extensions==0.4.3
nbconvert==5.6.0
nbformat==4.4.0
nbsphinx==0.6.1
networkx==2.4
nltk==3.5
nodeenv==1.3.5
notebook==6.0.1
nr.collections==0.0.1
nr.databind==0.0.4
nr.interface==0.0.2
nr.metaclass==0.0.5
nr.parsing.date==0.0.1
nr.pylang.utils==0.0.2
nr.stream==0.0.3
numpy==1.18.1
numpydoc==0.9.2
overrides==2.8.0
packaging==20.3
# Editable install with no version control (pandas==0.25.3)
-e /usr/local/lib/python3.7/site-packages
pandoc==1.0.2
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.5.1
pathtools==0.1.2
pexpect==4.7.0
pickleshare==0.7.5
Pillow==7.1.1
pkginfo==1.5.0.1
plac==0.9.6
plotly==4.1.1
pluggy==0.13.1
ply==3.11
pre-commit==2.2.0
preshed==2.0.1
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.11.3
ptyprocess==0.6.0
py==1.8.1
pycodestyle==2.5.0
pycparser==2.19
pydoc-markdown==3.0.0
pyflakes==2.1.1
PyGithub==1.44.1
Pygments==2.4.2
PyJWT==1.7.1
pymdown-extensions==7.1
pyparsing==2.4.2
pyrsistent==0.15.4
pytest==5.4.1
pytest-cov==2.8.1
python-dateutil==2.8.0
pytorch-pretrained-bert==0.6.2
pytorch-transformers==1.1.0
pytz==2019.3
PyYAML==5.3.1
pyzmq==18.1.0
qtconsole==4.5.5
readme-renderer==26.0
regex==2020.4.4
requests==2.22.0
requests-toolbelt==0.9.1
responses==0.10.14
retrying==1.3.3
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
s3transfer==0.3.3
sacremoses==0.0.41
scikit-learn==0.22.2.post1
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
sentencepiece==0.1.85
six==1.12.0
smmap==3.0.2
snowballstemmer==2.0.0
soupsieve==1.9.5
spacy==2.1.9
Sphinx==3.0.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sqlparse==0.3.1
srsly==1.0.2
tensorboardX==2.0
terminado==0.8.2
testpath==0.4.2
thinc==7.0.8
tokenizers==0.5.2
toml==0.10.0
torch==1.4.0
torchvision==0.5.0
tornado==6.0.3
tqdm==4.45.0
traitlets==4.3.3
transformers==2.8.0
twilio==6.33.0
twine==3.1.1
typed-ast==1.4.1
typing==3.7.4.1
typing-extensions==3.7.4.2
Unidecode==1.1.1
uritemplate==3.0.1
urllib3==1.25.6
virtualenv==20.0.18
wasabi==0.6.0
watchdog==0.10.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
word2number==1.1
wrapt==1.11.2
yarl==1.4.2
zipp==0.6.0
```

This is my system pip freeze, I'm having problems with setting up an environment as well :(

**Comment by epwalsh** [comment]
It looks like you have an old version of allennlp installed in your environment. Try the following:

```bash
pip uninstall --yes allennlp
make install
```

Then try building the docs again

**Comment by epwalsh** [comment]
Hey @Bharat123rox could you just resolve the conflict? (elmo command has been removed) Otherwise looks good!

**Pull request merged**
