### PR TITLE
Update torch requirement from <1.8.0,>=1.6.0 to >=1.6.0,<1.9.0

### PR DESCRIPTION
**Pull request by nelson-liu**
Playing dependabot for the day.

Updates the requirements on [torch](https://github.com/pytorch/pytorch) to permit the latest version.

Release Notes: https://github.com/pytorch/pytorch/releases/tag/v1.8.0

### CODE REVIEW

**Comment by nelson-liu** [comment]
This is ready to look at, I think someone needs to go into the github settings and modify the required check from `Docker (CUDA 11.0) ` to `Docker (CUDA 11.1) ` to get rid of the expected check.

**Comment by dirkgr** [comment]
I don't know why the expected check is there. Those are not configured in the settings. They are configured in the files in `.github`, which you already fixed.

**Comment by nelson-liu** [comment]
Hmm, I thought they're at https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule#creating-a-branch-protection-rule (step 7)

**Comment by dirkgr** [comment]
Oh, you are right! I fixed it.

**Review by dirkgr — APPROVED** [review]

**Comment by dirkgr** [comment]
Thanks a lot! This is great!

**Comment by nelson-liu** [comment]
No problem, thanks for taking a look. I realize I erroneously upticked the torchvision version in the docker build to keep pace with pytorch, i'll open a PR to try to fix that requirement too.

**Pull request merged**
