### PR TITLE
add [CLS] and [SEP] tags to bert indexer

### LINKED ISSUE #2141: BERT indexer should add [CLS] and [SEP] tokens
as pointed out here: https://github.com/allenai/allennlp/pull/2067#issuecomment-444324303

in a quick and dirty experiment, that adds an extra point of validation f1 (94.1 -> 95.2) to my BERT + char NER model.

### PR DESCRIPTION
**Pull request by joelgrus**
fixes #2141 

as mentioned in the issue, this change gets an extra point of dev F1 on the NER model I trained with BERT embeddings + character embeddings

### CODE REVIEW

**Comment by joelgrus** [comment]
you can always just not pass in the offsets (i.e. not include them in the indexer-embedder map) and get back the per-wordpiece embeddings (including [CLS] and [SEP]) and do whatever you want with them.

I don't know that I'd consider that "cumbersome" but I guess it would depend on what you then needed to do with the embeddings.

**Comment by qiuwei** [comment]
Got it, thanks.

**Comment by joelgrus** [comment]
if it's a pretty common use case, we could also do something like add an optional flag to the `BertIndexer` that would include the offsets for the [CLS] and [SEP] tokens, and then normal usage would bring back (num_tokens + 2) BERT vectors for [CLS], token1, token2, ..., tokenk, [SEP]

**Comment by joelgrus** [comment]
if it's a pretty common use case, we could also do something like add an optional flag to the `BertIndexer` that would include the offsets for the [CLS] and [SEP] tokens, and then normal usage would bring back (num_tokens + 2) BERT vectors for [CLS], token1, token2, ..., tokenk, [SEP]

**Comment by matt-gardner** [comment]
Yeah, @joelgrus, I was thinking the same thing, that this could easily be an option.  If anyone seeing this wants this functionality, please speak up so we know how to prioritize it.  Or just submit a PR adding it =).

**Pull request merged**
