### PR TITLE
fixed the fix-endpoint_span_extractor issue

### LINKED ISSUE #3416: EndpointSpanExtractor should check that input matches input_dim
Currently, the EndpointSpanExtractor will happily take input that doesn't match its passed-in `input_dim` if the exclusive span indices are not being used. Feels like there should maybe be a check somewhere for this...https://github.com/allenai/allennlp/blob/master/allennlp/modules/span_extractors/endpoint_span_extractor.py

### PR DESCRIPTION
**Pull request by nadgeri14**
Fixes #3416. Check for dimensions in EndpointSpanExtractor when use_exclusive_start_indices = False.

### CODE REVIEW

**Comment by matt-gardner** [comment]
@nelson-liu, do you mind if I assign this to you?  You have the most context on this PR.  It looks to me like the logic is fine, but you'd know for sure.

@nadgeri14, this is failing CI because the line you added is too long.  Can you break it up into multiple lines?  You'll also want to run `black` on the file, to be sure it meets our formatting requirements.  I'd also recommend using `f""` strings instead of `"".format()`.

**Comment by nadgeri14** [comment]
@matt-gardner Thank you for reviewing the PR :) I will make the necessary changes as suggested. 

@matt-gardner @nelson-liu  **What is the best method**: Should I update the existing PR or create a new PR

Thanks for the help :D

**Comment by matt-gardner** [comment]
Just update this PR.

**Comment by nelson-liu** [comment]
instead of using assert, can you use an `if` block and raise a `ValueError`?

**Comment by nadgeri14** [comment]
@nelson-liu  Yea, I will change it for sure :) 
What should be an idea error message, for now, I have written it as: 
**Dimension mismatch expected ({input_size}) received ({input_dimension}).**

**Comment by nelson-liu** [comment]
Thanks @nadgeri14 , much appreciated!!

**Comment by nadgeri14** [comment]
@nelson-liu Thankyou, would not have been possible without your help :D

**Pull request merged**
