### PR TITLE
specify 'truncation' to avoid transformers warning

### PR DESCRIPTION
**Pull request by epwalsh**
Avoids this warning message: https://github.com/allenai/allennlp/discussions/5119#discussioncomment-605823

### CODE REVIEW

**Comment by epwalsh** [comment]
@nelson-liu GitHub won't let me assign you as a reviewer, but I would appreciate a review if you have time.

**Comment by nelson-liu** [comment]
LGTM, thanks! worth adding a quick test to ensure that this is explicit?

**Comment by epwalsh** [comment]
> worth adding a quick test to ensure that this is explicit?

We do have a test in place to make sure the output is truncated. I also tried capturing logs and stderr from HuggingFace in that test using pytest's `capsys` and `caplog` fixtures, but neither of those worked for some reason.

**Comment by epwalsh** [comment]
When we removed the `truncation` parameter (https://github.com/allenai/allennlp/commit/55cfb47b5a0c84fa9ae97b792f82805919a0149a), we had `transformers` pinned to 3.x. Now we have it pinned to 4.x, so I think this is okay.

**Review by dirkgr — APPROVED** [review]
LGTM, if you sign off on 9555b2c.

I don't understand how we can be setting `stride` when we return only one flat list of tokens. How is that supposed to work?

**Comment by epwalsh** [comment]
> I don't understand how we can be setting stride when we return only one flat list of tokens. How is that supposed to work?

Yea, I don't know why we have that. I'm removing it.

**Pull request merged**
