### PR TITLE
Replace scripts with entry_points.console_scripts

### PR DESCRIPTION
**Pull request by sodre**
The recommended approach to create launch scripts is to use entry_points
  and console_scripts.

  xref: https://packaging.python.org/guides/distributing-packages-using-setuptools/#scripts

### CODE REVIEW

**Comment by sodre** [comment]
Hi folks, I am happy to fix the error this caused if I had access to the CI build logs. Any chance someone can post the error messages here?

**Comment by nelson-liu** [comment]
If you press "log in as guest" on the teamcity login page you might be seeing, you might be able to access the logs? let me know if that doesn't work, and i'll put it in a gist.

**Comment by sodre** [comment]
👓

**Comment by sodre** [comment]
Hi @nelson-liu, I fixed the build error. Unfortunately, I am not sure if the there is an easy way to get the unit-tests to hit the target of the changes.

Would you mind reviewing the PR as is?

**Comment by schmmd** [comment]
@sodre thank you for the PR!  You'll want to update all the references to `bin/allennlp` in the repository before this can be merged:

```
$ git grep 'bin/allennlp'
MANIFEST.in:include bin/allennlp
README.md:You can test your installation with `bin/allennlp test-install`.
README.md:with the `allennlp` command (if you installed via `pip`) or `bin/allennlp` (if you installed via source).
allennlp/tests/commands/main_test.py:        sys.argv = ["bin/allennlp",
```

**Comment by schmmd** [comment]
I think you'll need to add `pip install --editable .` to the Dockerfile since the previous method for running AllenNLP in that container was `bin/allennlp`.  The new approach seems better!

**Comment by schmmd** [comment]
@sodre do you intend to make the requested changes?  This is close to being merged but my last two comments need to be addressed.

**Comment by sodre** [comment]
@schmmd, yes I intend on making the changes. I will have time to work on it tomorrow and Friday. What is the cutting date for the next release?

**Comment by schmmd** [comment]
@sodre awesome--just checking.

We don't have a date for a next release but we're likely to cut a point release relatively soon (over the next couple of weeks).

**Comment by schmmd** [comment]
@joelgrus I finished out the remaining changes in the PR.  Would you CR?

I tested this with `pip install git+git://github.com/sodre/allennlp.git@0029274f76c9205c43602485e0dd0525e25b29c6`.

**Pull request merged**
