### PR TITLE
Pad tokens to make number of tokens 8x

### PR DESCRIPTION
**Pull request by mahnerak**
This addresses issue #4868.

The torch.amp automatically enabled mixed-precision training but on the latest GPUs, it's faster (according to the documentation) because of Tensor Cores. But latter is enabled (almost) for fp16 calculations if the tensor dimensions are multiple of 8.
Reference[1]: https://developer.nvidia.com/blog/optimizing-gpu-performance-tensor-cores/

The embedding size and the batch size is easy to maintain as multiples of 8 manually. This PR makes the number of tokens multiple of any given number.
The only thing to do is to provide extra `{"pad_to_multiple_of": 8}` to the `token_indexer` config.

P.S. I did not observe a significant boost in performance. According to Figure 3 of [1] it sometimes can work fast even for tensors with axis sizes non-divisible by 8, depends on the architecture.

### CODE REVIEW

**Comment by epwalsh** [comment]
@mahnerak, what kind of GPU did you benchmark this on?

Even if we don't observe a speed up on the GPUs we have at hand, I think it's a good addition to the library given that there should be an improvement on *some* GPUs, in theory at least.

**Comment by epwalsh** [comment]
And as you mentioned in https://github.com/allenai/allennlp/issues/4868, we should also have this feature for the `MaxTokensBatchSampler`.

**Comment by mahnerak** [comment]
@epwalsh I've been testing it on Titan V gpus.

I'll make a comparison table before making this draft ready for reviews, on Titan V, RTX3080 and GTX1080Ti (the latter doesn't have Tensor Cores).

**Comment by epwalsh** [comment]
Cool. Well we also have access to A100s so I could potentially run benchmarks on one of those.

**Comment by epwalsh** [comment]
What type of model are you using to benchmark?

The [NVIDIA post](https://developer.nvidia.com/blog/optimizing-gpu-performance-tensor-cores/) suggests that it could be important for the vocab size to be multiple of 8 as well 😒 That would be harder to control.

**Comment by dirkgr** [comment]
Any progress on these? I'd be interested in having this if it makes a measurable difference.

**Comment by JohnGiorgi** [comment]
This would also be useful for certain transformer models that use block sparse attention, like BigBird, as they require the sequence length to be divisible by the block size (see https://huggingface.co/transformers/model_doc/bigbird.html).

**Pull request closed without merging**
