### PR TITLE
Allow W&B anon mode

### PR DESCRIPTION
**Pull request by epwalsh**
`WANDB_API_KEY` no longer required (although still recommended).

If you don't provide this key, you may get prompted to choose what to do:

image

### CODE REVIEW

**Comment by dirkgr** [comment]
... and if you don't have wandb installed at all, none of this happens, right?

**Comment by dirkgr** [comment]
@vanpelt, what do you think?

**Review by dirkgr — APPROVED** [review]

**Comment by epwalsh** [comment]
> ... and if you don't have wandb installed at all, none of this happens, right?

Currently W&B is listed as a dependency. Although I think we should make it an optional dependency (same for tensorboard). Regardless, this is a trainer callback and so is only used if it's listed in the config file. This PR doesn't address that feature.

**Comment by epwalsh** [comment]
What's not ideal about this is that you are prompted for input. If you were running this in a non-interactive environment (like Beaker batch) this wouldn't work.

**Comment by dirkgr** [comment]
Does it detect when it's not running on a terminal?

**Pull request merged**
