### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by matt-gardner** [comment]
Looks good, except doing this as a single PR doesn't work, because we only allow squash commits.

**Comment by schmmd** [comment]
Note there is already [a tag](https://github.com/allenai/allennlp/releases/tag/v0.3.0) on commit https://github.com/allenai/allennlp/pull/615/commits/5ecb40c3dc56a81fe92680d36db9ea9d482ffbff.

Once this is merged I will:

* Make a PyPi release.
* Make sure the Docker image is rebuilt.
* Deploy our documentation.

After all that, I'll assign a PR amending our documentation to Matt and Joel.

**Comment by matt-gardner** [comment]
Commit 5ecb40c will disappear once this is merged.  This _squashes_ the commits into a single commit.  You need to separate this into two PRs.

**Comment by schmmd** [comment]
@matt-gardner yes, I understand.  I just hadn't thought of that.

**Comment by schmmd** [comment]
I removed the second commit from this PR.

**Comment by matt-gardner** [comment]
Ah, sorry, looks like github's UI didn't update to show me the removed commit.  I still think the particular commit you have will be erased, so you'll have to retag it, but that's fine.

**Pull request merged**
