### PR TITLE
DeprecationWarning removed for op-level token_embedders

### LINKED ISSUE #2252: Timeline for deprecating top-level token_embedders?
Specifying token embedders for a BasicTextFieldEmbedder as top-level key-value pairs has been deprecated for awhile now---when are we thinking of removing it for good? Perhaps soon, since the config wizard is out?

Regardless, if we aren't going to immediately remove it, we should probably update the warning https://github.com/allenai/allennlp/blob/3f0953d19de3676ea82e642659fc96d90690e34d/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L141-L143 to indicate the version it was deprecated, and the version it will be removed.

### PR DESCRIPTION
**Pull request by pidugusundeep**
Fixes #2252

### CODE REVIEW

**Comment by matt-gardner** [comment]
Thanks! You need to also remove the check for the `DeprecationWarning` in the test that's failing.

**Comment by pidugusundeep** [comment]
> Thanks! You need to also remove the check for the `DeprecationWarning` in the test that's failing.

Got it, Removed the test and added a PR

**Comment by pidugusundeep** [comment]
> Thanks! You need to also remove the check for the `DeprecationWarning` in the test that's failing.

Got it, Removed the test and added a PR

**Comment by matt-gardner** [comment]
Sorry I wasn't clear - we still want the test for the old format, because we still handle the old format.  We just need to remove the check for the _warning_ from the test, because the warning doesn't appear anymore.  So it's just removing what was line 215, and un-indenting the line below it.

**Comment by pidugusundeep** [comment]
> Sorry I wasn't clear - we still want the test for the old format, because we still handle the old format. We just need to remove the check for the _warning_ from the test, because the warning doesn't appear anymore. So it's just removing what was line 215, and un-indenting the line below it.

Got it attached a PR

**Comment by matt-gardner** [comment]
Thanks!

**Pull request merged**
