### PR TITLE
gitignore doc artifacts so you can easily build docs locally

### PR DESCRIPTION
**Pull request by epwalsh**
This just makes it so you can build the docs locally without having to clean up after yourself. The biggest change is renaming `mkdocs.yml` to `mkdocs-skeleton.yml`. I'm not sure if that's the best name though.

### CODE REVIEW

**Comment by schmmd** [comment]
image

Our build system seems to depend on this file existing.  I agree with your change though--it's annoying that you need to carefully not check in this file.  Someone on our side would probably need to look into how to modify our build system to get this changed though.

**Comment by epwalsh** [comment]
@schmmd I think I might have fixed it

**Comment by schmmd** [comment]
👍

**Comment by epwalsh** [comment]
No worries!

**Pull request merged**
