### PR TITLE
Revert "drop support for Python 3.6"

### PR DESCRIPTION
**Pull request by epwalsh**
Reverts allenai/allennlp#5012. We've decided to keep 3.6 for now since Google Collab only supports 3.6.

### CODE REVIEW

**Comment by epwalsh** [comment]
CC @KoichiYasuoka

**Comment by epwalsh** [comment]
I'm going to go ahead and merge this since it's a simple "revert X" PR that we've already agreed on and it's blocking other things.

**Comment by nelson-liu** [comment]
ironically, colab is on 3.7 now. Is there a particular reason for dropping 3.6, though?

**Comment by epwalsh** [comment]
🤦‍♂️

This was one reason: https://github.com/allenai/allennlp/issues/4707

But now I think we'll just keep support for 3.6 as long as our major dependencies (like PyTorch) still support it.

**Comment by dirkgr** [comment]
They updated to 3.6 one day after this?

I will choose to believe they did it because of us 🌊.

**Pull request merged**
