### PR TITLE
Use a Python base image.

### PR DESCRIPTION
**Pull request by schmmd**
* Remove conda.
* Use Debian instead of Ubuntu.

This trims another 200 MB from our Docker file.

```
~/h/a/allennlp (python-docker $%) docker images                                                                                                                                                                                     (allennlp) 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
allennlp/allennlp   python-jesse        74f6e1cbc41e        36 minutes ago      2.45GB
allennlp/allennlp   latest              547826cf4c97        About an hour ago   2.64GB
python              3.6.3-jessie        be512ebcbac9        5 days ago          690MB
```

### CODE REVIEW

**Comment by schmmd** [comment]
@DeNeutoy @joelgrus any objections?

I still need to try this image on a GPU.  @DeNeutoy what test do you run to validate Docker images on GPU machines?  I would probably just run an evaluation with GPUs enabled.

**Comment by joelgrus** [comment]
as long as it works, I have no objections 😀

**Comment by DeNeutoy** [comment]
@schmmd I just train one of the models for a few epochs and check it's using the GPU. You can do this via kube if you change all the absolute paths from beaker to `/net/efs/aristo/dlfa/...`.

2 questions:
- Why debian instead of ubuntu (not a problem I just don't know)?
- My concern with not using the miniconda installation route is that we have 2 ways to install with python (directly via docker and indirectly via conda if a user isn't using docker), which might create more work for us.

**Comment by schmmd** [comment]
@DeNeutoy -- Debian is smaller than Ubuntu by a 100 or 200 MB and has everything we need.  Python doesn't build a base image with Ubuntu.  I believe it's discouraged because of how large the Ubuntu base image is.

You have a reasonable concern about having multiple ways to install Python.  I favor this change regardless because:

* This simplifies our Docker build and makes it easier to troubleshoot issues.
* This allows us to pin the exact version of Python.
* We've had problems with `conda` in our Docker build in the past.
* `conda` and Docker are redundant technologies.
* Our Docker build is smaller by 200 MB.

**Comment by schmmd** [comment]
I would also add that I don't trust conda enough to say that our two solutions (using conda on Mac desktop and using conda on a Ubuntu Docker image) are consistent enough to avoid problems.

**Comment by schmmd** [comment]
Evaluations work and use a GPU.

**Pull request merged**
