### PR TITLE
Adding a registry for things we want to be able to create from parameters.

### PR DESCRIPTION
**Pull request by matt-gardner**
I added the main functionality to `util` so we can really easily create new registry decorators, for models, token_indexers, tokenizers, etc.  If this looks good, I'll update the PR for all of the places we have these dictionaries.

For cases where there's an `OrderedDict`, to have a default, I'll not use the decorator for the implementation we want to be the default, and add it to the dictionary manually, to be sure it gets added first (and add comments to code for why these particular implementations don't follow the norm).

### CODE REVIEW

**Comment by joelgrus** [comment]
I also prefer snake-cased keys for things like this.

the bare `dict`s we've been using for these have never sat right with me. Is it worth it at this point to make a `Registry` class that exposes typed decorators / accessors? e.g.

```
class Registry:

    def register_dataset_reader(self, name: str, dataset_reader: DatasetReader):
    """this is a decorator"""
        ...

    def get_dataset_reader(self, name: str) -> DatasetReader:
    """call this instead of importing the dict"""
```

and then

```
@registry.register_dataset_reader("snli")
class SnliDatasetReader(DatasetReader):
    ...
```

**Comment by matt-gardner** [comment]
I don't really have a strong opinion on "language modeling" vs. "language_modeling" for the keys, I'm fine switching it.  And sure, I can make a `Registry` class, and put it in `experiments/`.

**Comment by matt-gardner** [comment]
Ok, this is now done, @joelgrus and @DeNeutoy, if one of you wants to take another look.  I talked with Joel about this in person on Friday, and to remove circular imports we decided it'd work best to just move the abstract API class to the base module, with concrete implementations in their own separate module (e.g., `data/token_indexer.py`, and `data/token_indexers/single_id_token_indexer.py`).  So there are a number of classes that got moved up a module, and a bunch of imports changed to match.  The number of meaningfully-changed lines here is actually smaller than it looks.

**Comment by joelgrus** [comment]
I like this approach, it's much cleaner. But I'm not a huge fan of methods that have nearly identical names but do different things, e.g.

```
def get_dataset_reader(cls, name: str) -> Type[DatasetReader]:
def get_dataset_readers(cls) -> List[str]:
```

Maybe call the second one `list_dataset_readers`? Or `available_dataset_readers`? Or something else, I'm not sure what, just to more clearly distinguish it from `get_dataset_reader`?

**Comment by DeNeutoy** [comment]
Looks great, thanks for switching those tests over to not use the dicts, that was on my to do list for a while.

**Pull request merged**
