### PR TITLE
remove callback trainer

### PR DESCRIPTION
**Pull request by DeNeutoy**
Removing this so that #3700  is a bit easier, but we are planning to integrate the callbacks into the original trainer.

### CODE REVIEW

**Comment by bryant1410** [comment]
(related to #3519)

**Comment by DeNeutoy** [comment]
Thanks!

**Comment by viking-sudo-rm** [comment]
Curious since I have been using custom callbacks to implement magnitude pruning: is the plan to reintegrate all existing callbacks, or only a subset of them? My use case in particular depends on end of epoch and end of training

**Comment by matt-gardner** [comment]
Please comment on #3519 with some more detail on what exactly you would like to keep, and we'll see what we can do.  I had a list of things I was going to do, and modifying `grad_clipping` and `grad_norm` didn't make the list, but if there's demand for generalizing that functionality, we can maybe figure that out.

**Pull request merged**
