### PR TITLE
Remove large openie model file

### PR DESCRIPTION
**Pull request by gabrielStanovsky**
- Remove large Open IE model file (~30mb), which was pushed accidentally.
- Use SRL's fixture model instead, in testing the Open IE predictor.

### CODE REVIEW

**Comment by gabrielStanovsky** [comment]
Addresses #1754

**Comment by huntzhan** [comment]
Hi team, this file still exists in the git history. To remove it entirely, the admin could follow [this](https://gist.github.com/magnetikonline/dd5837d597722c9c2d5dfa16d8efe5b9) and [this](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) guides. The change requires `push --force` and should be done by admin of repo only.

```
➜  allennlp tempFile=$(mktemp)
IFS=$'\n'
for commitSHA1 in $(git rev-list --all); do
        git ls-tree -r --long "$commitSHA1" >>"$tempFile"
done
➜  allennlp sort --key 3 "$tempFile" | \
        uniq | \
        sort --key 4 --numeric-sort --reverse

100644 blob 194477803731209e32b5a16191d664e22ce7abad 34068339	allennlp/tests/fixtures/open_information_extraction/serialization/model.tar.gz
100644 blob ea037c6f6e2ab04231056ef148e033677a7e6e4c 8720384	allennlp/tests/fixtures/data/atis/atis.db
100644 blob ad35b7aaaa57cf05bba25a49136061422d659825 1373369	allennlp/service/static/lib/babel.min.js
100644 blob 8e0d573308083a7ee686b397e5bd959ec407d7cb  653066	allennlp/service/static/lib/react-dom.js
100644 blob bb4fac0613755cbada5c903a9e13df57dfa9b4c4  450896	tests/fixtures/elmo/lm_weights.hdf5
100644 blob bb4fac0613755cbada5c903a9e13df57dfa9b4c4  450896	allennlp/tests/fixtures/elmo/lm_weights.hdf5
100644 blob 6ba3daa16db3aa4b9bb26ca34835b931b845db60  450896	tests/fixtures/elmo/lm_weights.hdf5
100644 blob fff1752d3097ddc9ab2e0ff9a8bbdf13b0550be3  435427	tutorials/how_to/visualization_images/bidaf_attention_demo.png
100644 blob 18b950bed672780fdce06d7d6249d14147a0e67c  395659	tutorials/how_to/visualization_images/wikitables_overview.png
100644 blob ed8e8bb91956965ebfba0462f8e9e0483ebff459  207828	tests/fixtures/data/triviaqa-sample.tgz
100644 blob ed8e8bb91956965ebfba0462f8e9e0483ebff459  207828	allennlp/tests/fixtures/data/triviaqa-sample.tgz
100644 blob 987e696a7ead69b16071b8d9d56df57f97120f4b  175690	tutorials/how_to/debugging_images/inspect_variable.png
100644 blob fe862c48571cb01b6a554fdcb1ac400aed9fdd21  160897	tutorials/getting_started/data/cr.train
```

**Comment by nelson-liu** [comment]
@huntzhan thanks for bringing this up --- the decision was made to not change the git history through force-pushing (also see https://github.com/allenai/allennlp/issues/1757#issuecomment-420694130)

**Comment by huntzhan** [comment]
@nelson-liu got it, thank you for your clarification.

**Pull request merged**
