### PR TITLE
Adding ability to choose validation DatasetReader with "predict"

### PR DESCRIPTION
**Pull request by danieldeutsch**
Here is my proposal for #2949. It is a non-breaking change. It changes the `--use-dataset-reader` flag from a boolean to a string with an optional value which specifies which reader to use and defaults to "train".

I am not thrilled with the testing, but short of creating a custom model archive just for this change, I could not think of a better solution.

If you all are happy with this, I will make it style-compliant, etc.

### CODE REVIEW

**Comment by matt-gardner** [comment]
If we want this to be backwards compatible for the behavior of that flag, I'm ok with this implementation.  I would probably go a bit farther, though, and make the default value be `validation` instead of `train` (and change the order that you check things when loading, to fall back to train if validation is not present) - it just makes more sense, and it's a very minor point for backwards incompatibility.

**Comment by schmmd** [comment]
@danieldeutsch what do you think about @matt-gardner 's question?

**Comment by danieldeutsch** [comment]
I am ok with whatever you all think is best.

One issue with my implementation that I found in my own scripts is that `argparse` can't correctly parse the command if the `--use-dataset-reader` flag comes just before the config file because it interprets the config file name as the argument for `--use-dataset-reader`. For example `allennlp predict --use-dataset-reader config.jsonnet input.jsonl`

I can think of a few ways around this. (1) We make the `train` or `validation` value to `--use-dataset-reader` required, but this would be a breaking change to anyone who uses the flag. (2) We make `--use-dataset-reader` use the validation reader by default and introduce a second argument that can override this decision. (3) We introduce a new flag `--use-validation-dataset-reader` and leave the original flag alone.

What do you all think?

**Comment by matt-gardner** [comment]
My preference would be to just make the behavior of `predict` identical to the behavior of `evaluate`: https://github.com/allenai/allennlp/blob/083f3430b8cee77e3c1c553f4cba70ad8f3594b1/allennlp/commands/evaluate.py#L137-L146

That is, always use the validation dataset reader if it's available, and fall back to the training one, with no option to override that.

**Comment by danieldeutsch** [comment]
I disagree with no option to override the choice. The specific scenario that I need this for is transfer learning in which the training and testing tasks are different. I still want to be able to run `predict` in the training scenario as well as the testing scenario so I can measure how well the model does on the training task on a held-out dataset.

**Comment by matt-gardner** [comment]
Ok, fair enough.  I was going to wait for someone specifically requesting the ability to change it to add the feature; looks like that's now.  Then I would vote for your option (2).

**Comment by danieldeutsch** [comment]
Sorry for the delay.

I switched the default dataset reader to the validation one and added a new flag to override that choice. One thing which could be nice (but not implemented) is to not quietly fall back to the training dataset reader if the user explicitly requests to use a validation dataset reader which does not exist.

**Pull request merged**
