### PR TITLE
Moved checkpointing after check for whether to break for early stopping.

### LINKED ISSUE #5076: 1 model state file left when num_serialized_models_to_keep=0 and patience used
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

If `num_serialized_models_to_keep` is set to 0 and the model stops early due to running out of patience, it leaves one model state file behind in the serialization directory. The expected behavior is that there are no model state files left in this directory (as is the case when training is not stopped due to running out of patience).

I can quickly submit a PR to fix this.

## Related issues or possible duplicates

- https://github.com/allenai/allennlp/pull/2880/commits 
  - Though this is different because the present issue only emerging when the model stops training due to running out of patience.

## Environment

OS: Linux

Python version: 3.8.5

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
aiohttp==3.7.4.post0
-e git+git@github.com:ksteimel/allennlp.git@59b92106443ff6ce26776beef5259dee3a422b40#egg=allennlp
allennlp-models==2.1.0
appdirs==1.4.3
async-timeout==3.0.1
attrs==20.3.0
beautifulsoup4==4.9.3
blis==0.4.1
boto3==1.17.22
botocore==1.20.22
CacheControl==0.12.6
catalogue==1.0.0
certifi==2019.11.28
chardet==3.0.4
click==7.1.2
colorama==0.4.3
configparser==5.0.2
conllu==4.4
contextlib2==0.6.0
coverage==5.5
cycler==0.10.0
cymem==2.0.5
distlib==0.3.0
distro==1.4.0
docker-pycreds==0.4.0
filelock==3.0.12
ftfy==5.9
future==0.18.2
gitdb==4.0.7
GitPython==3.1.14
google==3.0.0
grpcio==1.36.1
h5py==3.2.1
html5lib==1.0.1
idna==2.8
iniconfig==1.1.1
ipaddr==2.2.0
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
jsonnet==0.17.0
jsonpickle==2.0.0
jsonschema==3.2.0
kiwisolver==1.3.1
lmdb==1.1.1
lockfile==0.12.2
MarkupSafe==1.1.1
matplotlib==3.4.0
more-itertools==8.7.0
msgpack==0.6.2
multidict==5.1.0
murmurhash==1.0.5
nltk==3.5
numpy==1.20.1
overrides==3.1.0
packaging==20.3
pandas==1.2.3
pathtools==0.1.2
pathy==0.4.0
pep517==0.8.2
Pillow==8.1.2
plac==1.1.3
pluggy==0.13.1
preshed==3.0.5
progress==1.5
promise==2.3
protobuf==3.15.5
psutil==5.8.0
py==1.10.0
py-rouge==1.1
py-spy==0.3.5
pydantic==1.7.3
pyparsing==2.4.6
pyrsistent==0.17.3
pytest==6.2.2
pytest-cov==2.11.1
python-dateutil==2.8.1
pytoml==0.1.21
pytz==2021.1
PyYAML==5.4.1
ray==0.8.6
redis==3.4.1
regex==2020.11.13
requests==2.22.0
retrying==1.3.3
s3transfer==0.3.4
sacremoses==0.0.43
scikit-learn==0.24.1
scipy==1.6.1
seaborn==0.11.1
sentencepiece==0.1.95
sentry-sdk==1.0.0
shortuuid==1.0.1
six==1.14.0
smart-open==3.0.0
smmap==4.0.0
soupsieve==2.2.1
spacy==2.2.4
spacy-legacy==3.0.1
srsly==1.0.5
subprocess32==3.5.4
tabulate==0.8.9
tensorboardX==2.1
thinc==7.4.0
threadpoolctl==2.1.0
tokenizers==0.10.1
toml==0.10.2
torch==1.7.1
torchvision==0.8.2
tqdm==4.59.0
transformers==4.3.3
typer==0.3.2
typing-extensions==3.7.4.3
urllib3==1.25.8
wandb==0.10.23
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
word2number==1.1
yarl==1.6.3
```

</p>
</details>

## Steps to reproduce
Here is a minimal config file that causes this issue:
```
{
    "dataset_reader": {
        "type": "classification-tsv",
        "token_indexers": {"tokens": {"type": "single_id"}}
    },
    "train_data_path": "../../../quick_start/data/movie_review/train.tsv",
    "validation_data_path": "../../../quick_start/data/movie_review/dev.tsv",
    "model": {
        "type": "simple_classifier",
        "embedder": {
            "token_embedders": {"tokens": {"type": "embedding", "embedding_dim": 10}}
        },
        "encoder": {"type": "bag_of_embeddings", "embedding_dim": 10}
    },
    "data_loader": {"batch_size": 8, "shuffle": true},
    "trainer": {"optimizer": "adam", "num_epochs": 50, "patience": 1, "checkpointer" : {"num_serialized_models_to_keep": 0}}
}
```
This minimal config uses the example and model from [part 1 of the allennlp-guide](https://github.com/allenai/allennlp-guide/blob/master/exercises/part1/training-and-prediction/config_setup.py).

### PR DESCRIPTION
**Pull request by ksteimel**
Fixes #5076 .

Changes proposed in this pull request:

- Reorder so that model is saved after check to see if we've ran out of patience.

### CODE REVIEW

**Comment by dirkgr** [comment]
I suspect that moving the barrier makes multi-GPU training hang, but there is also #5088, so I'm trying this out to see if it's this change, or some other issue that makes it hang.

**Comment by dirkgr** [comment]
Looks like it hangs even without this change. I'll want to fix the hang first, because touching the barriers is always a bit dangerous.

**Comment by ksteimel** [comment]
Ah I think this is actually related to #5067 . And I don't think my solution is right in that case.

**Comment by dirkgr** [comment]
I'm closing this because I think #5142 takes care of the issue without breaking the distributed case.

**Pull request closed without merging**
