### PR TITLE
Find the right embedding layer for mismatched cases

### PR DESCRIPTION
**Pull request by matt-gardner**
I was diagnosing an error in the interpret code for a scibert NER model, and found this.  Comments in the code should explain the problem and solution well enough, let me know if they don't.

### CODE REVIEW

**Comment by matt-gardner** [comment]
The model test failure here is actually a bug in the test that I need to fix.  It's a one-line change in the model repo.  What's the process for doing this, given that we're running model tests here, and I can't add a fix to this PR?

**Comment by epwalsh** [comment]
@matt-gardner just make a separate PR in the models repo. We can merge that into master and then re-run this workflow

**Comment by matt-gardner** [comment]
But that PR will fail tests without this change.

**Comment by epwalsh** [comment]
You could temporarily update the workflow in models CI to use your patch branch by modifying the `requirements.txt` file

**Comment by matt-gardner** [comment]
That seems pretty bad - I wouldn't want to merge such a PR into that repo.  I can see modifying the allennlp commit in the models repo to demonstrate that we have two PRs, one on each repo, that both work, before either one gets merged.  But I think we're going to have to live with the fact the we'll have a short window where one or the other CI is broken.  I'm not sure there's a reasonable alternative.  @dirkgr, do you see a way around this, either?

**Comment by epwalsh** [comment]
Personally I'm okay with one repo being broken for a few minutes

**Comment by matt-gardner** [comment]
Me too.  I'll make another PR for the model repo, to show that we have a fix for the breakage in this PR, then after this PR gets merged I can update the other PR to remove the CI hack, and merge the fix for the model repo tests.

**Comment by matt-gardner** [comment]
Ok, corresponding model PR: https://github.com/allenai/allennlp-models/pull/38.

**Pull request merged**
