### PR TITLE
Don't use a hard-coded temp directory.

### PR DESCRIPTION
**Pull request by schmmd**
Fixes https://github.com/allenai/allennlp/issues/1539 and makes AllenNLP less system-dependent.

### CODE REVIEW

**Comment by schmmd** [comment]
I thought this was causing an error on my local machine--but then it turns out I can't even run tests on master without increasing my `ulimit -n`.  This seems like a clear improvement--although I think it would be even better to have tests store results in independent directories.

**Comment by schmmd** [comment]
@joelgrus any suggestions on what I should name the static variable?

**Comment by joelgrus** [comment]
where do you clean up that directory ?

**Comment by schmmd** [comment]
@joelgrus look in `tearDown`.  It uses the same code as before to clean up the directory.

**Comment by joelgrus** [comment]
so the module when it first runs uses `mkdtemp` to create a tempdir. 

then every test creates again and deletes that same directory?

something feels slightly off about that, but I guess it works

**Comment by schmmd** [comment]
@joelgrus I agree it seems off--I see it as one step better from where we are now.  With the file leak issue in https://github.com/allenai/allennlp/issues/1563 I don't want to create one directory per test because we are not able to clean them up.

**Pull request merged**
