### PR TITLE
Add pytorch to requirements, so readthedocs can build

### PR DESCRIPTION
**Pull request by matt-gardner**

### CODE REVIEW

**Comment by matt-gardner** [comment]
@joelgrus, @schmmd, @DeNeutoy, any objections to this?

**Comment by schmmd** [comment]
Well, it makes it harder for new users to start using allennlp because they now need to modify `requirements.txt`.  I'm not a fan of this change.

This also likely affects one of our Docker builds--as they install either gpu/cpu PyTorch.

**Comment by matt-gardner** [comment]
I think eventually the plan for users will be to just do `pip install allennlp` and be done.  Those requirements are specified in yet a third place, which is just in `setup.py`.  You could even imagine the docker image just pip-installing `allennlp`...

An alternative to what I have here: a `readthedocs_requirements.txt`.

**Comment by joelgrus** [comment]
I would prefer a separate `readthedocs_requirements.txt`, if ReadTheDocs is happy with that

**Comment by schmmd** [comment]
I prefer `readthedocs_requirements.txt` as well.

**Pull request merged**
