### PR TITLE
Add optional FeedForward to BasicClassifier

### PR DESCRIPTION
**Pull request by nelson-liu**

### CODE REVIEW

**Comment by nelson-liu** [comment]
Thanks for the quick turnaround, @matt-gardner

**Comment by matt-gardner** [comment]
I happened to check my email one minute after you submitted the PR.  You got lucky =).

**Comment by lwgkzl** [comment]
when i want to classify some word using cnn, i  meet this error.  
"allennlp.common.checks.ConfigurationError: "Extra parameters passed to BasicClassifier: {'feedforward': {'activations': 'relu', 'dropout': 0.1, 'hidden_dims': 20, 'input_dim': 16, 'num_layers': 1}} "
here is my json file:
 "model": {
    "type": "basic_classifier",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
            "type": "embedding",
            "embedding_dim": 128
        }
      }
    },
    "seq2vec_encoder": {
      "type": "cnn",
    "embedding_dim":128,
    "num_filters":64,
    "ngram_filter_sizes": [2]
    },
    "num_labels": 162,
    "feedforward": {
      "input_dim": 64,
      "num_layers": 2,
      "hidden_dims": 128,
      "activations":"relu"
    },
    "dropout": 0.5
  }
Is there anything wrong in my code?  thank u~

**Comment by nelson-liu** [comment]
you need to install from latest master to get this change, since it hasn't made it into a release yet i think

**Comment by lwgkzl** [comment]
> you need to install from latest master to get this change, since it hasn't made it into a release yet i think

Thank you~

**Pull request merged**
